//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntreev.Crema.ServiceModel.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EventResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EventResources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ntreev.Crema.ServiceModel.Properties.EventResources", typeof(EventResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; added &apos;{3}({4})&apos; to the user list of database &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddAccessMemberToDataBase {
            get {
                return ResourceManager.GetString("AddAccessMemberToDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; added &apos;{3}&apos; to the user list of table item &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddAccessMemberToTableItem {
            get {
                return ResourceManager.GetString("AddAccessMemberToTableItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; added &apos;{3}&apos; to the user list of type item &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddAccessMemberToTypeItem {
            get {
                return ResourceManager.GetString("AddAccessMemberToTypeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; banned user &apos;{2}({3})&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BanUser {
            get {
                return ResourceManager.GetString("BanUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; created domain &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BeginDomain {
            get {
                return ResourceManager.GetString("BeginDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; has canceled domain &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CancelDomain {
            get {
                return ResourceManager.GetString("CancelDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; changed contents of Table &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeTableContent {
            get {
                return ResourceManager.GetString("ChangeTableContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; changed template of Table &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeTableTemplate {
            get {
                return ResourceManager.GetString("ChangeTableTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; changed template of Type &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeTypeTemplate {
            get {
                return ResourceManager.GetString("ChangeTypeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; changed information of user &apos;{2}({3})&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeUserInfo {
            get {
                return ResourceManager.GetString("ChangeUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; created database &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CreateDataBase {
            get {
                return ResourceManager.GetString("CreateDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; created table &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CreateTable {
            get {
                return ResourceManager.GetString("CreateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; created table path &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CreateTableCategory {
            get {
                return ResourceManager.GetString("CreateTableCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; created type &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CreateType {
            get {
                return ResourceManager.GetString("CreateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; created type path &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CreateTypeCategory {
            get {
                return ResourceManager.GetString("CreateTypeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; created user &apos;{2}({3})&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; created user path &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CreateUserCategory {
            get {
                return ResourceManager.GetString("CreateUserCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; deleted database &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteDataBase {
            get {
                return ResourceManager.GetString("DeleteDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; deleted table &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteTable {
            get {
                return ResourceManager.GetString("DeleteTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; deleted table path &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteTableCategory {
            get {
                return ResourceManager.GetString("DeleteTableCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; deleted type &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteType {
            get {
                return ResourceManager.GetString("DeleteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; deleted type path &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteTypeCategory {
            get {
                return ResourceManager.GetString("DeleteTypeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; deleted user &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; deleted user path &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteUserCategory {
            get {
                return ResourceManager.GetString("DeleteUserCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; has exited domain &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EndDomain {
            get {
                return ResourceManager.GetString("EndDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; has entered database &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EnterDataBase {
            get {
                return ResourceManager.GetString("EnterDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; has entered domain &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EnterDomainUser {
            get {
                return ResourceManager.GetString("EnterDomainUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; kicked &apos;{2}({3})&apos; from domain &apos;{4}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KickDomainUser {
            get {
                return ResourceManager.GetString("KickDomainUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; kicked user &apos;{2}({3})&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KickUser {
            get {
                return ResourceManager.GetString("KickUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; has left database &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LeaveDataBase {
            get {
                return ResourceManager.GetString("LeaveDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; has left domain &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LeaveDomainUser {
            get {
                return ResourceManager.GetString("LeaveDomainUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; has activated database &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LoadDataBase {
            get {
                return ResourceManager.GetString("LoadDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; locked database: &quot;{2}&quot;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LockDataBase {
            get {
                return ResourceManager.GetString("LockDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; locked table item.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LockTableItem {
            get {
                return ResourceManager.GetString("LockTableItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; locked type item.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LockTypeItem {
            get {
                return ResourceManager.GetString("LockTypeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; has logged in crema service.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LoginUser {
            get {
                return ResourceManager.GetString("LoginUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; has logged out crema service.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LogoutUser {
            get {
                return ResourceManager.GetString("LogoutUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; moved table &apos;{2}&apos; from &apos;{3}&apos; to &apos;{4}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MoveTable {
            get {
                return ResourceManager.GetString("MoveTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; moved table path &apos;{2}&apos; from &apos;{3}&apos; to &apos;{4}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MoveTableCategory {
            get {
                return ResourceManager.GetString("MoveTableCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; moved type &apos;{2}&apos; from &apos;{3}&apos; to &apos;{4}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MoveType {
            get {
                return ResourceManager.GetString("MoveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; moved type path &apos;{2}&apos; from &apos;{3}&apos; to &apos;{4}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MoveTypeCategory {
            get {
                return ResourceManager.GetString("MoveTypeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; moved user &apos;{2}({3})&apos; from &apos;{4}&apos; to &apos;{5}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MoveUser {
            get {
                return ResourceManager.GetString("MoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; moved user path &apos;{2}&apos; from &apos;{3}&apos; to &apos;{4}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MoveUserCategory {
            get {
                return ResourceManager.GetString("MoveUserCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; notified to &apos;{2}&apos;.
        ///notification : &quot;{3}&quot;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotifyMessage {
            get {
                return ResourceManager.GetString("NotifyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reason과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; removed &apos;{3}&apos; to the user list of database &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RemoveAccessMemberFromDataBase {
            get {
                return ResourceManager.GetString("RemoveAccessMemberFromDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; removed &apos;{3}&apos; to the user list of table item &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RemoveAccessMemberFromTableItem {
            get {
                return ResourceManager.GetString("RemoveAccessMemberFromTableItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; removed &apos;{3}&apos; to the user list of type item &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RemoveAccessMemberFromTypeItem {
            get {
                return ResourceManager.GetString("RemoveAccessMemberFromTypeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; renamed  database &apos;{2}&apos; to &apos;{3}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RenameDataBase {
            get {
                return ResourceManager.GetString("RenameDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; renamed  table &apos;{2}&apos; to &apos;{3}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RenameTable {
            get {
                return ResourceManager.GetString("RenameTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; renamed  table path &apos;{2}&apos; to &apos;{3}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RenameTableCategory {
            get {
                return ResourceManager.GetString("RenameTableCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; renamed  type &apos;{2}&apos; to &apos;{3}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RenameType {
            get {
                return ResourceManager.GetString("RenameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; renamed  type path &apos;{2}&apos; to &apos;{3}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RenameTypeCategory {
            get {
                return ResourceManager.GetString("RenameTypeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; renamed  user path &apos;{2}&apos; to &apos;{3}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RenameUserCategory {
            get {
                return ResourceManager.GetString("RenameUserCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   database &apos;{2}&apos; reset by &apos;{0}({1})&apos;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResetDataBase {
            get {
                return ResourceManager.GetString("ResetDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   database &apos;{2}&apos; is resetting by &apos;{0}({1})&apos;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResettingDataBase {
            get {
                return ResourceManager.GetString("ResettingDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; revert revision of database &apos;{2}&apos; to &apos;{3}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RevertDataBase {
            get {
                return ResourceManager.GetString("RevertDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; send message &apos;{2}({3})&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; set type of &apos;{3}&apos; user of database &apos;{2}&apos; to &apos;{4}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetAccessMemberOfDataBase {
            get {
                return ResourceManager.GetString("SetAccessMemberOfDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}({1})&apos; set type of &apos;{3}&apos; user of table item &apos;{2}&apos; to &apos;{4}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetAccessMemberOfTableItem {
            get {
                return ResourceManager.GetString("SetAccessMemberOfTableItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}({1})&apos; set type of &apos;{3}&apos; user of type item &apos;{2}&apos; to &apos;{4}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetAccessMemberOfTypeItem {
            get {
                return ResourceManager.GetString("SetAccessMemberOfTypeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; set owner of domain &apos;{4}&apos; to &apos;{2}({3})&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetDomainOwner {
            get {
                return ResourceManager.GetString("SetDomainOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; set authority of database &apos;{2}&apos; to private.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetPrivateDataBase {
            get {
                return ResourceManager.GetString("SetPrivateDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; set authority of table item &apos;{2}&apos; to private.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetPrivateTableItem {
            get {
                return ResourceManager.GetString("SetPrivateTableItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; set authority of type item &apos;{2}&apos; to private.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetPrivateTypeItem {
            get {
                return ResourceManager.GetString("SetPrivateTypeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; set authority of database &apos;{2}&apos; to public.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetPublicDataBase {
            get {
                return ResourceManager.GetString("SetPublicDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; set authority of table item &apos;{2}&apos; to public.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetPublicTableItem {
            get {
                return ResourceManager.GetString("SetPublicTableItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; set authority of type item &apos;{2}&apos; to public.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetPublicTypeItem {
            get {
                return ResourceManager.GetString("SetPublicTypeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; unbanned user &apos;{2}({3})&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UnbanUser {
            get {
                return ResourceManager.GetString("UnbanUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; has inactivated database &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UnloadDataBase {
            get {
                return ResourceManager.GetString("UnloadDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; unlocked database.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UnlockDataBase {
            get {
                return ResourceManager.GetString("UnlockDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; unlocked table item.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UnlockTableItem {
            get {
                return ResourceManager.GetString("UnlockTableItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}({1})&apos; unlocked type item.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UnlockTypeItem {
            get {
                return ResourceManager.GetString("UnlockTypeItem", resourceCulture);
            }
        }
    }
}
