//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntreev.Crema.ServiceModel.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ntreev.Crema.ServiceModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   It&apos;s already locked.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_AlreadyLocked {
            get {
                return ResourceManager.GetString("Exception_AlreadyLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is already set to private.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_AlreadyPrivate {
            get {
                return ResourceManager.GetString("Exception_AlreadyPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is already set to public.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_AlreadyPublic {
            get {
                return ResourceManager.GetString("Exception_AlreadyPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   authentication does not signed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_AuthenticationDoesNotSigned {
            get {
                return ResourceManager.GetString("Exception_AuthenticationDoesNotSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to add user because it is set to public.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_CannotAddToPublic {
            get {
                return ResourceManager.GetString("Exception_CannotAddToPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot to move to the same folder.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_CannotMoveToSameFolder {
            get {
                return ResourceManager.GetString("Exception_CannotMoveToSameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to remove user because it is set to public.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_CannotRemoveToPublic {
            get {
                return ResourceManager.GetString("Exception_CannotRemoveToPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not rename to same name.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_CannotRename {
            get {
                return ResourceManager.GetString("Exception_CannotRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot to set itself as template.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_CannotSetTemplateItself {
            get {
                return ResourceManager.GetString("Exception_CannotSetTemplateItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot to set template to inherited table.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_CannotSetTemplateToInherited {
            get {
                return ResourceManager.GetString("Exception_CannotSetTemplateToInherited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find category path &apos;{0}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_CategoryNotFound_Format {
            get {
                return ResourceManager.GetString("Exception_CategoryNotFound_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find database &apos;{0}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_DataBaseNotFound_Format {
            get {
                return ResourceManager.GetString("Exception_DataBaseNotFound_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find domain ID &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_DomainNotFound_Format {
            get {
                return ResourceManager.GetString("Exception_DomainNotFound_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You do not have permission to perform과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_HaveNotPermission {
            get {
                return ResourceManager.GetString("Exception_HaveNotPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inherited child table cannot delete.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_InheritedChildCannotDelete {
            get {
                return ResourceManager.GetString("Exception_InheritedChildCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inherited child table cannot move.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_InheritedChildCannotMove {
            get {
                return ResourceManager.GetString("Exception_InheritedChildCannotMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inherited child table cannot rename.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_InheritedChildCannotRename {
            get {
                return ResourceManager.GetString("Exception_InheritedChildCannotRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inherited private item cannot add user과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_InheritedPrivateItemCannotAdd {
            get {
                return ResourceManager.GetString("Exception_InheritedPrivateItemCannotAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inherited private item cannot remove user과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_InheritedPrivateItemCannotRemove {
            get {
                return ResourceManager.GetString("Exception_InheritedPrivateItemCannotRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid ID or invalid path.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_InvalidIDorPath {
            get {
                return ResourceManager.GetString("Exception_InvalidIDorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find item &apos;{0}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_ItemNotFound_Format {
            get {
                return ResourceManager.GetString("Exception_ItemNotFound_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It&apos;s not locked.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_NotLocked {
            get {
                return ResourceManager.GetString("Exception_NotLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Root folder cannot move과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_RootFolderCannotMove {
            get {
                return ResourceManager.GetString("Exception_RootFolderCannotMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Root folder cannot rename.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_RootFolderCannotRename {
            get {
                return ResourceManager.GetString("Exception_RootFolderCannotRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find table &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_TableNotFound_Format {
            get {
                return ResourceManager.GetString("Exception_TableNotFound_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find type &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_TypeNotFound_Format {
            get {
                return ResourceManager.GetString("Exception_TypeNotFound_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find UserID &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_UserNotFound_Format {
            get {
                return ResourceManager.GetString("Exception_UserNotFound_Format", resourceCulture);
            }
        }
    }
}
