//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntreev.Crema.Designer.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ntreev.Crema.Designer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   변경(_A)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Change {
            get {
                return ResourceManager.GetString("Button_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   닫기(_C)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   생성(_O)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경(_C)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   카테고리과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Category {
            get {
                return ResourceManager.GetString("Label_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Comment {
            get {
                return ResourceManager.GetString("Label_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 변경 일자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ContentModifiedDateTime {
            get {
                return ResourceManager.GetString("Label_ContentModifiedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 변경자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ContentModifier {
            get {
                return ResourceManager.GetString("Label_ContentModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   플래그 집합과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_IsFlag {
            get {
                return ResourceManager.GetString("Label_IsFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   편집 날짜과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ModifiedDateTime {
            get {
                return ResourceManager.GetString("Label_ModifiedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   편집한 사람과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Modifier {
            get {
                return ResourceManager.GetString("Label_Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Path {
            get {
                return ResourceManager.GetString("Label_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   테이블 이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TableName {
            get {
                return ResourceManager.GetString("Label_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   태그과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Tags {
            get {
                return ResourceManager.GetString("Label_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   부모 템플릿과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TemplatedParent {
            get {
                return ResourceManager.GetString("Label_TemplatedParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   형태 변경 일자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TemplateModifiedDateTime {
            get {
                return ResourceManager.GetString("Label_TemplateModifiedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   형태 변경자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TemplateModifier {
            get {
                return ResourceManager.GetString("Label_TemplateModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   타입 이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TypeName {
            get {
                return ResourceManager.GetString("Label_TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   자식 테이블 추가(_C)...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_AddChildTable {
            get {
                return ResourceManager.GetString("MenuItem_AddChildTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사본 만들기(_V)...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Copy {
            get {
                return ResourceManager.GetString("MenuItem_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제(_D)...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Delete {
            get {
                return ResourceManager.GetString("MenuItem_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   내용 편집(_E)...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_EditContent {
            get {
                return ResourceManager.GetString("MenuItem_EditContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   형태 편집(_D)...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_EditTemplate {
            get {
                return ResourceManager.GetString("MenuItem_EditTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   찾기(_F)...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Find {
            get {
                return ResourceManager.GetString("MenuItem_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상속된 테이블 만들기(_I)...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Inherit {
            get {
                return ResourceManager.GetString("MenuItem_Inherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이동(_M)...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Move {
            get {
                return ResourceManager.GetString("MenuItem_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새 폴더(_N)...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_NewFolder {
            get {
                return ResourceManager.GetString("MenuItem_NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새 테이블(_T)...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_NewTable {
            get {
                return ResourceManager.GetString("MenuItem_NewTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새 타입(_T)...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_NewType {
            get {
                return ResourceManager.GetString("MenuItem_NewType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름 변경(_M)...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Rename {
            get {
                return ResourceManager.GetString("MenuItem_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   타입 브라우저에서 보기(_V)...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_SelectInTypeBrowser {
            get {
                return ResourceManager.GetString("MenuItem_SelectInTypeBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경중입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Progress_Change {
            get {
                return ResourceManager.GetString("Progress_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   폴더 삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_DeleteCategory {
            get {
                return ResourceManager.GetString("Title_DeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   테이블 형태 변경과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_EditTableTemplate {
            get {
                return ResourceManager.GetString("Title_EditTableTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   타입 편집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_EditTypeTemplate {
            get {
                return ResourceManager.GetString("Title_EditTypeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새 테이블과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_NewTable {
            get {
                return ResourceManager.GetString("Title_NewTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   테이블 이름 변경과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_RenameTable {
            get {
                return ResourceManager.GetString("Title_RenameTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   타입 이름 변경과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_RenameType {
            get {
                return ResourceManager.GetString("Title_RenameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   테이블 열 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TableColumnInfo {
            get {
                return ResourceManager.GetString("Title_TableColumnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   테이블 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TableInfo {
            get {
                return ResourceManager.GetString("Title_TableInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용되고 있는 테이블들과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TablesBeingUsed {
            get {
                return ResourceManager.GetString("Title_TablesBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   타입 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TypeInfo {
            get {
                return ResourceManager.GetString("Title_TypeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용되고 있는 타입들과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TypesBeingUsed {
            get {
                return ResourceManager.GetString("Title_TypesBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   열기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tool_Open {
            get {
                return ResourceManager.GetString("Tool_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tool_Save {
            get {
                return ResourceManager.GetString("Tool_Save", resourceCulture);
            }
        }
    }
}
