//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntreev.Crema.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ntreev.Crema.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Item &apos;{0}&apos; is already existed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_AlreadyExistedItem_Format {
            get {
                return ResourceManager.GetString("Exception_AlreadyExistedItem_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; is already a valid type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_AreadyExistedDataType_Format {
            get {
                return ResourceManager.GetString("Exception_AreadyExistedDataType_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You must have at least one column.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_AtLeastOneColumn {
            get {
                return ResourceManager.GetString("Exception_AtLeastOneColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   At least one key must be set.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_AtLeastOneKey {
            get {
                return ResourceManager.GetString("Exception_AtLeastOneKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can not add a child table.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_CannotAddChildTable {
            get {
                return ResourceManager.GetString("Exception_CannotAddChildTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can not add a inherited table.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_CannotAddInheritedTable {
            get {
                return ResourceManager.GetString("Exception_CannotAddInheritedTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not convert &apos;{0}&apos; to &apos;{1}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_CannotConvert_Format {
            get {
                return ResourceManager.GetString("Exception_CannotConvert_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not copy to same DataSet.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_CannotCopyToSameDataSet {
            get {
                return ResourceManager.GetString("Exception_CannotCopyToSameDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not delete as type is referenced.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_CannotDeleteAsTypeIsReferenced {
            get {
                return ResourceManager.GetString("Exception_CannotDeleteAsTypeIsReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can not edit an inherited table.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_CannotEditInheritedTable {
            get {
                return ResourceManager.GetString("Exception_CannotEditInheritedTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If the table is not in DataSet, it can not be inherited.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_CannotInheritWithoutDataSet {
            get {
                return ResourceManager.GetString("Exception_CannotInheritWithoutDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value &apos;{0}&apos; is not defined in type &apos;{1}&apos; and can not be converted.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_CannotParseEnum_Format {
            get {
                return ResourceManager.GetString("Exception_CannotParseEnum_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can not remove a child table.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_CannotRemoveChildTable {
            get {
                return ResourceManager.GetString("Exception_CannotRemoveChildTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name can not contain any special characters \ / : *? &quot; &lt; &gt; |과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_InvalidName {
            get {
                return ResourceManager.GetString("Exception_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; is a name that can not be used.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_NameCannotBeUsed_Format {
            get {
                return ResourceManager.GetString("Exception_NameCannotBeUsed_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of fields does not match the number of columns of the table.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_NotEqualsFieldCountAndColumnCount {
            get {
                return ResourceManager.GetString("Exception_NotEqualsFieldCountAndColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attribute &apos;{0}&apos; does not exist.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_NotFoundAttribute_Format {
            get {
                return ResourceManager.GetString("Exception_NotFoundAttribute_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column &apos;{0}&apos; does not exist in table.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_NotFoundColumn_Format {
            get {
                return ResourceManager.GetString("Exception_NotFoundColumn_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path &apos;{0}&apos; was not found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_NotFoundDirectory_Format {
            get {
                return ResourceManager.GetString("Exception_NotFoundDirectory_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not included in DataSet.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_NotIncludedInDataSet {
            get {
                return ResourceManager.GetString("Exception_NotIncludedInDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not use &apos;{0}&apos; as the name &apos;Attributes&apos; because it is reserved.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_ReservedAttributeName_Format {
            get {
                return ResourceManager.GetString("Exception_ReservedAttributeName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not use &apos;{0}&apos; as the name &apos;Column&apos; because it is reserved.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_ReservedColumnName_Format {
            get {
                return ResourceManager.GetString("Exception_ReservedColumnName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; is not available because it is reserved.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_ReservedName_Format {
            get {
                return ResourceManager.GetString("Exception_ReservedName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type &apos;{0}&apos; can not be used.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_TypeCannotBeUsed_Format {
            get {
                return ResourceManager.GetString("Exception_TypeCannotBeUsed_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is still a table for the children that have not been resolved.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_UnresolvedChildTablesExist {
            get {
                return ResourceManager.GetString("Exception_UnresolvedChildTablesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is a problem that has not been solved yet.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_UnresolvedProblemsExist {
            get {
                return ResourceManager.GetString("Exception_UnresolvedProblemsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only usable on child table.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exception_UsableOnChildTable {
            get {
                return ResourceManager.GetString("Exception_UsableOnChildTable", resourceCulture);
            }
        }
    }
}
