//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ------------------------------------------------------------------------------
// dataBase: default
// revision: 9
// requested revision: -1
// devmode: False
// hash value: 3998a3547e53aee42e930ff46ca45fa8ba7f3ea3
// tags: All
// ------------------------------------------------------------------------------
namespace Ntreev.Crema.Code
{
    using Ntreev.Crema.Code.Reader;
    
    
    // Creator: admin
    // CreatedDateTime: 12/17/2019 5:22:57 AM
    // Modifier: admin
    // ModifiedDateTime: 12/17/2019 5:23:04 AM
    public enum Type1
    {
        
        // Creator: admin
        // CreatedDateTime: 12/17/2019 5:23:02 AM
        // Modifier: admin
        // ModifiedDateTime: 12/17/2019 5:23:02 AM
        Member1 = 0,
        
        // Creator: admin
        // CreatedDateTime: 12/17/2019 5:23:03 AM
        // Modifier: admin
        // ModifiedDateTime: 12/17/2019 5:23:03 AM
        Member2 = 1,
        
        // Creator: admin
        // CreatedDateTime: 12/17/2019 5:23:04 AM
        // Modifier: admin
        // ModifiedDateTime: 12/17/2019 5:23:04 AM
        Member3 = 2,
    }
}
