//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntreev.Crema.Client.Base.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ntreev.Crema.Client.Base.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   C_hange과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Change {
            get {
                return ResourceManager.GetString("Button_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Copy...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Copy {
            get {
                return ResourceManager.GetString("Button_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Create과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Enter {
            get {
                return ResourceManager.GetString("Button_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log In과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Login {
            get {
                return ResourceManager.GetString("Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can not select a database without logging in.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotSelectWithoutLoggingIn {
            get {
                return ResourceManager.GetString("Exception_CannotSelectWithoutLoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Connection Item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InvalidConnectionItem {
            get {
                return ResourceManager.GetString("Exception_InvalidConnectionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; is a non-existent data base.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_NonExistentDataBase {
            get {
                return ResourceManager.GetString("Exception_NonExistentDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Connection Item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_AddConnectionItem {
            get {
                return ResourceManager.GetString("Label_AddConnectionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Address과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Address {
            get {
                return ResourceManager.GetString("Label_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BranchRevision과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_BranchRevision {
            get {
                return ResourceManager.GetString("Label_BranchRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BranchSource과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_BranchSource {
            get {
                return ResourceManager.GetString("Label_BranchSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BranchSourceRevision과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_BranchSourceRevision {
            get {
                return ResourceManager.GetString("Label_BranchSourceRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Comment {
            get {
                return ResourceManager.GetString("Label_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ConnectionList {
            get {
                return ResourceManager.GetString("Label_ConnectionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created DateTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CreatedDateTime {
            get {
                return ResourceManager.GetString("Label_CreatedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creator과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Creator {
            get {
                return ResourceManager.GetString("Label_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DataBase과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_DataBase {
            get {
                return ResourceManager.GetString("Label_DataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DateTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_DateTime {
            get {
                return ResourceManager.GetString("Label_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Domain Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_DomainType {
            get {
                return ResourceManager.GetString("Label_DomainType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Connection Item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_EditConnectionItem {
            get {
                return ResourceManager.GetString("Label_EditConnectionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Etc과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Etc {
            get {
                return ResourceManager.GetString("Label_Etc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ID {
            get {
                return ResourceManager.GetString("Label_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Item Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ItemPath {
            get {
                return ResourceManager.GetString("Label_ItemPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Item Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ItemType {
            get {
                return ResourceManager.GetString("Label_ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manage Connection List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ManageConnectionItemList {
            get {
                return ResourceManager.GetString("Label_ManageConnectionItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified DateTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ModifiedDateTime {
            get {
                return ResourceManager.GetString("Label_ModifiedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modifier과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Modifier {
            get {
                return ResourceManager.GetString("Label_Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move To Wiki과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_MoveToWiki {
            get {
                return ResourceManager.GetString("Label_MoveToWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Owner과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Owner {
            get {
                return ResourceManager.GetString("Label_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Path {
            get {
                return ResourceManager.GetString("Label_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent Server List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_RecentServerList {
            get {
                return ResourceManager.GetString("Label_RecentServerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Connection Item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_RemoveConnectionItem {
            get {
                return ResourceManager.GetString("Label_RemoveConnectionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Revision과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Revision {
            get {
                return ResourceManager.GetString("Label_Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Save Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_SavePassword {
            get {
                return ResourceManager.GetString("Label_SavePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ServerList {
            get {
                return ResourceManager.GetString("Label_ServerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting DateTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_SettingDateTime {
            get {
                return ResourceManager.GetString("Label_SettingDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Th_eme과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Theme {
            get {
                return ResourceManager.GetString("Label_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_User {
            get {
                return ResourceManager.GetString("Label_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UserID {
            get {
                return ResourceManager.GetString("Label_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _About과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_About {
            get {
                return ResourceManager.GetString("MenuItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Change DataBase...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_ChangeDataBase {
            get {
                return ResourceManager.GetString("MenuItem_ChangeDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Copy...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Copy {
            get {
                return ResourceManager.GetString("MenuItem_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy DataBase...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_CopyDataBase {
            get {
                return ResourceManager.GetString("MenuItem_CopyDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Create DataBase...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_CreateDataBase {
            get {
                return ResourceManager.GetString("MenuItem_CreateDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Delete {
            get {
                return ResourceManager.GetString("MenuItem_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Delete DataBase...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_DeleteDataBase {
            get {
                return ResourceManager.GetString("MenuItem_DeleteDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Edit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Edit {
            get {
                return ResourceManager.GetString("MenuItem_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Enter {
            get {
                return ResourceManager.GetString("MenuItem_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_File {
            get {
                return ResourceManager.GetString("MenuItem_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Help과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Help {
            get {
                return ResourceManager.GetString("MenuItem_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Leave DataBase과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_LeaveDataBase {
            get {
                return ResourceManager.GetString("MenuItem_LeaveDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Load...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Load {
            get {
                return ResourceManager.GetString("MenuItem_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Lock...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Lock {
            get {
                return ResourceManager.GetString("MenuItem_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Login {
            get {
                return ResourceManager.GetString("MenuItem_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log _out과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Logout {
            get {
                return ResourceManager.GetString("MenuItem_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Manage DataBase...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_ManageDataBase {
            get {
                return ResourceManager.GetString("MenuItem_ManageDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set _Authority...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_SetAuthority {
            get {
                return ResourceManager.GetString("MenuItem_SetAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set _Private과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_SetPrivate {
            get {
                return ResourceManager.GetString("MenuItem_SetPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set _Public과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_SetPublic {
            get {
                return ResourceManager.GetString("MenuItem_SetPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Tools과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Tools {
            get {
                return ResourceManager.GetString("MenuItem_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Unload...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Unload {
            get {
                return ResourceManager.GetString("MenuItem_Unload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Unlock과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Unlock {
            get {
                return ResourceManager.GetString("MenuItem_Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to close DataBase?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_CloseDataBase {
            get {
                return ResourceManager.GetString("Message_CloseDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to set it to Private?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ConfirmToSetPrivate {
            get {
                return ResourceManager.GetString("Message_ConfirmToSetPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connecting to server. please wait a second.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ConnectingToServer {
            get {
                return ResourceManager.GetString("Message_ConnectingToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to connect to the server. Check your address.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ConnectionFailed {
            get {
                return ResourceManager.GetString("Message_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New database has been copied.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_CopiedDataBase {
            get {
                return ResourceManager.GetString("Message_CopiedDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New database is being copied.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_CopingDataBase {
            get {
                return ResourceManager.GetString("Message_CopingDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New database has been created.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_CreatedNewDataBase {
            get {
                return ResourceManager.GetString("Message_CreatedNewDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New database is being created.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_CreatingNewDataBase {
            get {
                return ResourceManager.GetString("Message_CreatingNewDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleted.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Deleted {
            get {
                return ResourceManager.GetString("Message_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading DataBase.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_LoadingDataBase {
            get {
                return ResourceManager.GetString("Message_LoadingDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to log out?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Logout {
            get {
                return ResourceManager.GetString("Message_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receiving information.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ReceivingInfo {
            get {
                return ResourceManager.GetString("Message_ReceivingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receiving Information.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ReceivingInformation {
            get {
                return ResourceManager.GetString("Message_ReceivingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Same ID is being connected. Would you like to disconnect and connect?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_SameIDConnected {
            get {
                return ResourceManager.GetString("Message_SameIDConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are users using the database. Do you want to close it anyway?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_VerifyToCloseDataBase {
            get {
                return ResourceManager.GetString("Message_VerifyToCloseDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access Information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_AccessInfo {
            get {
                return ResourceManager.GetString("Title_AccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Connection Item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_AddConnectionItem {
            get {
                return ResourceManager.GetString("Title_AddConnectionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy Connection Item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_CopyConnectionItem {
            get {
                return ResourceManager.GetString("Title_CopyConnectionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy DataBase과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_CopyDataBase {
            get {
                return ResourceManager.GetString("Title_CopyDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create DataBase과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_CreateDataBase {
            get {
                return ResourceManager.GetString("Title_CreateDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DataBase과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_DataBase {
            get {
                return ResourceManager.GetString("Title_DataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DataBase Domain List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_DataBaseDomainList {
            get {
                return ResourceManager.GetString("Title_DataBaseDomainList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DataBase Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_DataBaseInfo {
            get {
                return ResourceManager.GetString("Title_DataBaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Domain Information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_DomainInfo {
            get {
                return ResourceManager.GetString("Title_DomainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Domain List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_DomainList {
            get {
                return ResourceManager.GetString("Title_DomainList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Domain User List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_DomainUserList {
            get {
                return ResourceManager.GetString("Title_DomainUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Connection Item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_EditConnectionItem {
            get {
                return ResourceManager.GetString("Title_EditConnectionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lock Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_LockInfo {
            get {
                return ResourceManager.GetString("Title_LockInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select DataBase과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_SelectDataBase {
            get {
                return ResourceManager.GetString("Title_SelectDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Start {
            get {
                return ResourceManager.GetString("Title_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View Log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_ViewLog {
            get {
                return ResourceManager.GetString("Title_ViewLog", resourceCulture);
            }
        }
    }
}
