//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntreev.Crema.RuntimeService.ServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ntreev.com", ConfigurationName="ServiceClient.IRuntimeService")]
    internal interface IRuntimeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IRuntimeService/GetCodeGenerationData", ReplyAction="http://www.ntreev.com/IRuntimeService/GetCodeGenerationDataResponse")]
        Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.Runtime.Generation.GenerationSet> GetCodeGenerationData(string dataBaseName, string tags, string filterExpression, string revision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IRuntimeService/GetDataGenerationData", ReplyAction="http://www.ntreev.com/IRuntimeService/GetDataGenerationDataResponse")]
        Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.Runtime.Serialization.SerializationSet> GetDataGenerationData(string dataBaseName, string tags, string filterExpression, bool isDevmode, string revision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IRuntimeService/GetMetaData", ReplyAction="http://www.ntreev.com/IRuntimeService/GetMetaDataResponse")]
        Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.Runtime.Generation.GenerationSet, Ntreev.Crema.Runtime.Serialization.SerializationSet> GetMetaData(string dataBaseName, string tags, string filterExpression, bool isDevmode, string revision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IRuntimeService/ResetData", ReplyAction="http://www.ntreev.com/IRuntimeService/ResetDataResponse")]
        Ntreev.Crema.ServiceModel.ResultBase ResetData(string dataBaseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IRuntimeService/GetRevision", ReplyAction="http://www.ntreev.com/IRuntimeService/GetRevisionResponse")]
        Ntreev.Crema.ServiceModel.ResultBase<string> GetRevision(string dataBaseName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IRuntimeServiceChannel : Ntreev.Crema.RuntimeService.ServiceClient.IRuntimeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class RuntimeServiceClient : System.ServiceModel.ClientBase<Ntreev.Crema.RuntimeService.ServiceClient.IRuntimeService>, Ntreev.Crema.RuntimeService.ServiceClient.IRuntimeService {
        
        public RuntimeServiceClient() {
        }
        
        public RuntimeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RuntimeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RuntimeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RuntimeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.Runtime.Generation.GenerationSet> GetCodeGenerationData(string dataBaseName, string tags, string filterExpression, string revision) {
            return base.Channel.GetCodeGenerationData(dataBaseName, tags, filterExpression, revision);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.Runtime.Serialization.SerializationSet> GetDataGenerationData(string dataBaseName, string tags, string filterExpression, bool isDevmode, string revision) {
            return base.Channel.GetDataGenerationData(dataBaseName, tags, filterExpression, isDevmode, revision);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.Runtime.Generation.GenerationSet, Ntreev.Crema.Runtime.Serialization.SerializationSet> GetMetaData(string dataBaseName, string tags, string filterExpression, bool isDevmode, string revision) {
            return base.Channel.GetMetaData(dataBaseName, tags, filterExpression, isDevmode, revision);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase ResetData(string dataBaseName) {
            return base.Channel.ResetData(dataBaseName);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase<string> GetRevision(string dataBaseName) {
            return base.Channel.GetRevision(dataBaseName);
        }
    }
}
