//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntreev.Crema.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ntreev.Crema.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   You can not delete a table that is the default template.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotDeleteBaseTemplateTable {
            get {
                return ResourceManager.GetString("Exception_CannotDeleteBaseTemplateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder could not be deleted because user exists.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotDeleteUserCategory {
            get {
                return ResourceManager.GetString("Exception_CannotDeleteUserCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to end editing.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotEndEdit {
            get {
                return ResourceManager.GetString("Exception_CannotEndEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It&apos;s already been commissioned.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_Commissioned {
            get {
                return ResourceManager.GetString("Exception_Commissioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Empty string cannot send.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_EmptyStringCannotSend {
            get {
                return ResourceManager.GetString("Exception_EmptyStringCannotSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It has been expired.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_Expired {
            get {
                return ResourceManager.GetString("Exception_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상속받은 테이블은 테이블의 형태를 변경할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InheritedTableCannotEditTemplate {
            get {
                return ResourceManager.GetString("Exception_InheritedTableCannotEditTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상속받은 테이블은 자식 테이블을 생성할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InheritedTableCannotNewChild {
            get {
                return ResourceManager.GetString("Exception_InheritedTableCannotNewChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}은(는) 잘못된 이름입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InvalidName_Format {
            get {
                return ResourceManager.GetString("Exception_InvalidName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is not valid object.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InvalidObject {
            get {
                return ResourceManager.GetString("Exception_InvalidObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is not valid password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InvalidPassword {
            get {
                return ResourceManager.GetString("Exception_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is not valid token과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InvalidToken {
            get {
                return ResourceManager.GetString("Exception_InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   잘못된 형식의 아이디입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InvalidUserID {
            get {
                return ResourceManager.GetString("Exception_InvalidUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그인 되어 있는 아이디는 삭제할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_LoggedInUserCannotDelete {
            get {
                return ResourceManager.GetString("Exception_LoggedInUserCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is not closed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_NotClosed {
            get {
                return ResourceManager.GetString("Exception_NotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User does not exists.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_NotExistsUser {
            get {
                return ResourceManager.GetString("Exception_NotExistsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It cannot work operation, because you are not in database과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_NotInDataBase {
            get {
                return ResourceManager.GetString("Exception_NotInDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You do not have permission to perform the operation.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_PermissionDenied {
            get {
                return ResourceManager.GetString("Exception_PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   같은 이름으로 변경할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_SameName {
            get {
                return ResourceManager.GetString("Exception_SameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   같은 이름의 테이블이 이미 존재합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_SameTableNameExist {
            get {
                return ResourceManager.GetString("Exception_SameTableNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   같은 이름의 타입이 이미 존재합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_SameTypeNameExist {
            get {
                return ResourceManager.GetString("Exception_SameTypeNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 테이블이 편집중입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_TableIsBeingEdited_Format {
            get {
                return ResourceManager.GetString("Exception_TableIsBeingEdited_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; 테이블은 형태 변경중입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_TableIsBeingSetup_Format {
            get {
                return ResourceManager.GetString("Exception_TableIsBeingSetup_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 타입이 편집중입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_TypeIsBeingEdited_Format {
            get {
                return ResourceManager.GetString("Exception_TypeIsBeingEdited_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 등록된 아이디입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_UserIDisAlreadyResitered {
            get {
                return ResourceManager.GetString("Exception_UserIDisAlreadyResitered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 접속중인 아이디입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_UserIDIsConnecting {
            get {
                return ResourceManager.GetString("Exception_UserIDIsConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아이디/패스워드가 틀렸습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_WrongIDOrPassword {
            get {
                return ResourceManager.GetString("Exception_WrongIDOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DomainContext initialize.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_DomainContextInitialize {
            get {
                return ResourceManager.GetString("Message_DomainContextInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DomainContext is created.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_DomainContextIsCreated {
            get {
                return ResourceManager.GetString("Message_DomainContextIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도메인 복구 완료 : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_DomainIsRestored_Format {
            get {
                return ResourceManager.GetString("Message_DomainIsRestored_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도메인 복구 실패 : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_DomainRestorationIsFailed_Format {
            get {
                return ResourceManager.GetString("Message_DomainRestorationIsFailed_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A crash was detected. The previous session did not exit normally.
        ///The server will automatically attempt to recover (repair) from a damaged data.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_DomainRestorationMessage {
            get {
                return ResourceManager.GetString("Message_DomainRestorationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;{0} detection. {1} restored. {2} failed.&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_DomainState_Format {
            get {
                return ResourceManager.GetString("Message_DomainState_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   테이블 로드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_LoadTables {
            get {
                return ResourceManager.GetString("Message_LoadTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   복구할 도메인이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_NotFoundDomainsToRestore {
            get {
                return ResourceManager.GetString("Message_NotFoundDomainsToRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} [Version {1}]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ProgramInfo {
            get {
                return ResourceManager.GetString("Message_ProgramInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ========== Restoration: Suceess {0}, Fail {1} ==========과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_RestoreResult_Format {
            get {
                return ResourceManager.GetString("Message_RestoreResult_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ===================  Service Start  ===================과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ServiceStart {
            get {
                return ResourceManager.GetString("Message_ServiceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   테이블 관리자 초기화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_TableContextInitialize {
            get {
                return ResourceManager.GetString("Message_TableContextInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   테이블 관리자 생성 완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_TableContextIsCreated {
            get {
                return ResourceManager.GetString("Message_TableContextIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   테이블 로딩 완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_TableLoadingIsCompleted {
            get {
                return ResourceManager.GetString("Message_TableLoadingIsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UserContext initialize.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_UserContextInitialize {
            get {
                return ResourceManager.GetString("Message_UserContextInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UserContext is created.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_UserContextIsCreated {
            get {
                return ResourceManager.GetString("Message_UserContextIsCreated", resourceCulture);
            }
        }
    }
}
