//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntreev.Crema.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ntreev.Crema.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &quot;admin&quot; only can change &quot;admin&quot; info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_AdminCanChangeAdminInfo {
            get {
                return ResourceManager.GetString("Exception_AdminCanChangeAdminInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Admin can not banned.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_AdminCannotBanned {
            get {
                return ResourceManager.GetString("Exception_AdminCannotBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Admin can not deleted.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_AdminCannotDeleted {
            get {
                return ResourceManager.GetString("Exception_AdminCannotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is already in database과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_AlreadyInDataBase {
            get {
                return ResourceManager.GetString("Exception_AlreadyInDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   At least one column must exist in the table.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_AtLeastOneColumnInTable {
            get {
                return ResourceManager.GetString("Exception_AtLeastOneColumnInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   At least one key must exist in the table.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_AtLeastOneKeyInTable {
            get {
                return ResourceManager.GetString("Exception_AtLeastOneKeyInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   At least one member must exist in the type.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_AtLeastOneMemberInType {
            get {
                return ResourceManager.GetString("Exception_AtLeastOneMemberInType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Banned user can not log in.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_BannedUserCannotLogin {
            get {
                return ResourceManager.GetString("Exception_BannedUserCannotLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can not ban yourself.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotBanYourself {
            get {
                return ResourceManager.GetString("Exception_CannotBanYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not change to old password.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotChangeToOldPassword {
            get {
                return ResourceManager.GetString("Exception_CannotChangeToOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can not change your authority.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotChangeYourAuthority {
            get {
                return ResourceManager.GetString("Exception_CannotChangeYourAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can not delete a table that is the default template.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotDeleteBaseTemplateTable {
            get {
                return ResourceManager.GetString("Exception_CannotDeleteBaseTemplateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not delete on create child table.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotDeleteOnCreateChildTable {
            get {
                return ResourceManager.GetString("Exception_CannotDeleteOnCreateChildTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not delete on create table.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotDeleteOnCreateTable {
            get {
                return ResourceManager.GetString("Exception_CannotDeleteOnCreateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not delete on create Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotDeleteOnCreateType {
            get {
                return ResourceManager.GetString("Exception_CannotDeleteOnCreateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not delete path with items.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotDeletePathWithItems {
            get {
                return ResourceManager.GetString("Exception_CannotDeletePathWithItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not delete type with used tables.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotDeleteTypeWithUsedTables {
            get {
                return ResourceManager.GetString("Exception_CannotDeleteTypeWithUsedTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder could not be deleted because user exists.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotDeleteUserCategory {
            get {
                return ResourceManager.GetString("Exception_CannotDeleteUserCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can not delete yourself.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotDeleteYourself {
            get {
                return ResourceManager.GetString("Exception_CannotDeleteYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to end editing.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotEndEdit {
            get {
                return ResourceManager.GetString("Exception_CannotEndEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can not kick yourself.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotKickYourself {
            get {
                return ResourceManager.GetString("Exception_CannotKickYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not move on create child table.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotMoveOnCreateChildTable {
            get {
                return ResourceManager.GetString("Exception_CannotMoveOnCreateChildTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not move on create table.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotMoveOnCreateTable {
            get {
                return ResourceManager.GetString("Exception_CannotMoveOnCreateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not move on create Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotMoveOnCreateType {
            get {
                return ResourceManager.GetString("Exception_CannotMoveOnCreateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not move to same path.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotMoveToSamePath {
            get {
                return ResourceManager.GetString("Exception_CannotMoveToSamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not rename.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotRename {
            get {
                return ResourceManager.GetString("Exception_CannotRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not rename on create child table과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotRenameOnCreateChildTable {
            get {
                return ResourceManager.GetString("Exception_CannotRenameOnCreateChildTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not rename on create table.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotRenameOnCreateTable {
            get {
                return ResourceManager.GetString("Exception_CannotRenameOnCreateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not rename on create Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotRenameOnCreateType {
            get {
                return ResourceManager.GetString("Exception_CannotRenameOnCreateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not send message to offline user.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotSendMessageToOfflineUser {
            get {
                return ResourceManager.GetString("Exception_CannotSendMessageToOfflineUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Child table can not copy.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_ChildTableCannotCopy {
            get {
                return ResourceManager.GetString("Exception_ChildTableCannotCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Child table can not create child table.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_ChildTableCannotCreateChildTable {
            get {
                return ResourceManager.GetString("Exception_ChildTableCannotCreateChildTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Child table can not edit.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_ChildTableCannotEdit {
            get {
                return ResourceManager.GetString("Exception_ChildTableCannotEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Child table can not inherit.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_ChildTableCannotInherit {
            get {
                return ResourceManager.GetString("Exception_ChildTableCannotInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Child tables can not read data independently.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_ChildTableCannotReadIndependently {
            get {
                return ResourceManager.GetString("Exception_ChildTableCannotReadIndependently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It&apos;s already been commissioned.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_Commissioned {
            get {
                return ResourceManager.GetString("Exception_Commissioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DataBase has been loaded.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_DataBaseHasBeenLoaded {
            get {
                return ResourceManager.GetString("Exception_DataBaseHasBeenLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DataBase has not been loaded.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_DataBaseHasNotBeenLoaded {
            get {
                return ResourceManager.GetString("Exception_DataBaseHasNotBeenLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DataBase &apos;{0}&apos; is already existed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_DataBaseIsAlreadyExisted_Format {
            get {
                return ResourceManager.GetString("Exception_DataBaseIsAlreadyExisted_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;default&apos; database can not delete.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_DefaultDataBaseCannotDelete {
            get {
                return ResourceManager.GetString("Exception_DefaultDataBaseCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;default&apos; database can not rename.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_DefaultDataBaseCannotRename {
            get {
                return ResourceManager.GetString("Exception_DefaultDataBaseCannotRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Empty dataset can not import.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_EmptyDataSetCannotImport {
            get {
                return ResourceManager.GetString("Exception_EmptyDataSetCannotImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Empty string cannot send.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_EmptyStringCannotSend {
            get {
                return ResourceManager.GetString("Exception_EmptyStringCannotSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Empty string is not allowed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_EmptyStringIsNotAllowed {
            get {
                return ResourceManager.GetString("Exception_EmptyStringIsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; path is already existed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_ExistsPath_Format {
            get {
                return ResourceManager.GetString("Exception_ExistsPath_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It has been expired.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_Expired {
            get {
                return ResourceManager.GetString("Exception_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Incorrect password.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_IncorrectPassword {
            get {
                return ResourceManager.GetString("Exception_IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상속받은 테이블은 테이블의 형태를 변경할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InheritedTableCannotEditTemplate {
            get {
                return ResourceManager.GetString("Exception_InheritedTableCannotEditTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inherited table can not inherit.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InheritedTableCannotInherit {
            get {
                return ResourceManager.GetString("Exception_InheritedTableCannotInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상속받은 테이블은 자식 테이블을 생성할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InheritedTableCannotNewChild {
            get {
                return ResourceManager.GetString("Exception_InheritedTableCannotNewChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inherited table can not set comment.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InheritedTableCannotSetComment {
            get {
                return ResourceManager.GetString("Exception_InheritedTableCannotSetComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inherited table can not set tags과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InheritedTableCannotSetTags {
            get {
                return ResourceManager.GetString("Exception_InheritedTableCannotSetTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inherited table template can not edit.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InheritedTableTemplateCannotEdit {
            get {
                return ResourceManager.GetString("Exception_InheritedTableTemplateCannotEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; is incorrect name.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InvalidName_Format {
            get {
                return ResourceManager.GetString("Exception_InvalidName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is not valid object.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InvalidObject {
            get {
                return ResourceManager.GetString("Exception_InvalidObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is not valid password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InvalidPassword {
            get {
                return ResourceManager.GetString("Exception_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is not valid token과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InvalidToken {
            get {
                return ResourceManager.GetString("Exception_InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is not valid UserID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InvalidUserID {
            get {
                return ResourceManager.GetString("Exception_InvalidUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; is already locked.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_ItemIsAlreadyLocked_Format {
            get {
                return ResourceManager.GetString("Exception_ItemIsAlreadyLocked_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; has been changed : &apos;{1}&apos; to &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_ItemPathChanged_Format {
            get {
                return ResourceManager.GetString("Exception_ItemPathChanged_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You do not have access to items in use: &apos;{0}&apos;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_ItemsPermissionDenined_Format {
            get {
                return ResourceManager.GetString("Exception_ItemsPermissionDenined_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is already being edited.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_ItIsAlreadyBeingEdited {
            get {
                return ResourceManager.GetString("Exception_ItIsAlreadyBeingEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It can not revert from loaded database.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_LoadedDataBaseCannotRevert {
            get {
                return ResourceManager.GetString("Exception_LoadedDataBaseCannotRevert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그인 되어 있는 아이디는 삭제할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_LoggedInUserCannotDelete {
            get {
                return ResourceManager.GetString("Exception_LoggedInUserCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no repository module to create과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_NoRepositoryModule {
            get {
                return ResourceManager.GetString("Exception_NoRepositoryModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is not closed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_NotClosed {
            get {
                return ResourceManager.GetString("Exception_NotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Revision &apos;{0}&apos; can not found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_NotFoundRevision_Format {
            get {
                return ResourceManager.GetString("Exception_NotFoundRevision_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It cannot work operation, because you are not in database과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_NotInDataBase {
            get {
                return ResourceManager.GetString("Exception_NotInDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Offline user can not kicked.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_OfflineUserCannotKicked {
            get {
                return ResourceManager.GetString("Exception_OfflineUserCannotKicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Online user&apos;s authority can not changed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_OnlineUserAuthorityCannotChanged {
            get {
                return ResourceManager.GetString("Exception_OnlineUserAuthorityCannotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Owner can not kicked과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_OwnerCannotKicked {
            get {
                return ResourceManager.GetString("Exception_OwnerCannotKicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path is not an empty directory.
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_PathIsNotEmptyDirectory {
            get {
                return ResourceManager.GetString("Exception_PathIsNotEmptyDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You do not have permission to perform the operation.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_PermissionDenied {
            get {
                return ResourceManager.GetString("Exception_PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not change to the same name.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_SameName {
            get {
                return ResourceManager.GetString("Exception_SameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A path with the same name already exists.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_SameNamePathExists {
            get {
                return ResourceManager.GetString("Exception_SameNamePathExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table with same name already exists.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_SameTableNameExist {
            get {
                return ResourceManager.GetString("Exception_SameTableNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type with same name already exists.
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_SameTypeNameExist {
            get {
                return ResourceManager.GetString("Exception_SameTypeNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; 테이블이 편집중입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_TableIsBeingEdited_Format {
            get {
                return ResourceManager.GetString("Exception_TableIsBeingEdited_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; 테이블은 형태 변경중입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_TableIsBeingSetup_Format {
            get {
                return ResourceManager.GetString("Exception_TableIsBeingSetup_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table is not being edited.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_TableIsNotBeingEdited {
            get {
                return ResourceManager.GetString("Exception_TableIsNotBeingEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table template is not being edited.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_TableTemplateIsNotBeingEdited {
            get {
                return ResourceManager.GetString("Exception_TableTemplateIsNotBeingEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; 타입이 편집중입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_TypeIsBeingEdited_Format {
            get {
                return ResourceManager.GetString("Exception_TypeIsBeingEdited_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type is not being edited.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_TypeIsNotBeingEdited {
            get {
                return ResourceManager.GetString("Exception_TypeIsNotBeingEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unsaved data can not edit.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_UnsavedDataCannotEdit {
            get {
                return ResourceManager.GetString("Exception_UnsavedDataCannotEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are domains that have not yet been saved: &apos;{0}&apos;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_UnsavedDomainsExists_Format {
            get {
                return ResourceManager.GetString("Exception_UnsavedDomainsExists_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 등록된 아이디입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_UserIDisAlreadyResitered {
            get {
                return ResourceManager.GetString("Exception_UserIDisAlreadyResitered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 접속중인 아이디입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_UserIDIsConnecting {
            get {
                return ResourceManager.GetString("Exception_UserIDIsConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User is already banned.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_UserIsAlreadyBanned {
            get {
                return ResourceManager.GetString("Exception_UserIsAlreadyBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User is not banned.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_UserIsNotBanned {
            get {
                return ResourceManager.GetString("Exception_UserIsNotBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; is not in domain.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_UserIsNotInDomain_Format {
            get {
                return ResourceManager.GetString("Exception_UserIsNotInDomain_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User is not logged in.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_UserIsNotLoggedIn {
            get {
                return ResourceManager.GetString("Exception_UserIsNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Incorrect UserID or password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_WrongIDOrPassword {
            get {
                return ResourceManager.GetString("Exception_WrongIDOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DomainContext initialize.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_DomainContextInitialize {
            get {
                return ResourceManager.GetString("Message_DomainContextInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DomainContext is created.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_DomainContextIsCreated {
            get {
                return ResourceManager.GetString("Message_DomainContextIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Domain restoration completed : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_DomainIsRestored_Format {
            get {
                return ResourceManager.GetString("Message_DomainIsRestored_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Domain restoration failed : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_DomainRestorationIsFailed_Format {
            get {
                return ResourceManager.GetString("Message_DomainRestorationIsFailed_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A crash was detected. The previous session did not exit normally.
        ///The server will automatically attempt to restore from a data not yet saved.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_DomainRestorationMessage {
            get {
                return ResourceManager.GetString("Message_DomainRestorationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;{0} detection. {1} restored. {2} failed.&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_DomainState_Format {
            get {
                return ResourceManager.GetString("Message_DomainState_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load Tables과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_LoadTables {
            get {
                return ResourceManager.GetString("Message_LoadTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no domains to restore.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_NotFoundDomainsToRestore {
            get {
                return ResourceManager.GetString("Message_NotFoundDomainsToRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} [Version {1}]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ProgramInfo {
            get {
                return ResourceManager.GetString("Message_ProgramInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ========= Restoration: Suceess {0}, Fail {1} ==========과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_RestoreResult_Format {
            get {
                return ResourceManager.GetString("Message_RestoreResult_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ===================  Service Start  ===================과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ServiceStart {
            get {
                return ResourceManager.GetString("Message_ServiceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table Context initialized.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_TableContextInitialize {
            get {
                return ResourceManager.GetString("Message_TableContextInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table Context created.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_TableContextIsCreated {
            get {
                return ResourceManager.GetString("Message_TableContextIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table Loading completed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_TableLoadingIsCompleted {
            get {
                return ResourceManager.GetString("Message_TableLoadingIsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UserContext initialize.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_UserContextInitialize {
            get {
                return ResourceManager.GetString("Message_UserContextInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UserContext is created.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_UserContextIsCreated {
            get {
                return ResourceManager.GetString("Message_UserContextIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   # .repository
        ///
        ///크레마 데이터가 실제로 저장되는 곳입니다. 이 폴더는 숨김 속성이 기본적으로 설정되어 있습니다.
        ///
        ///숨김 속성으로 설정되어 있는 만큼 매우 중요한 폴더이기 때문에 건들이지 않는것을 추천합니다.
        ///
        ///## databases
        ///데이터 베이스가 저장되는 곳입니다.
        ///## users
        ///사용자 정보가 저장되는 곳입니다.
        ///## repo
        ///저장소의 형태를 나타내는 단순 텍스트 파일이다. 지원되는 모듈 타입은 &apos;svn&apos;, &apos;git&apos; 2가지 입니다.
        ///## file
        ///저장소의 데이터 형태를 나타내는 단순 텍스트 파일이다. 기본값은 &apos;xml&apos; 입니다.
        ///
        ///
        ///# caches
        ///크레마 시작시 빠른 실행을 위해서 각종 캐시 파일이 저장되어 있는 곳입니다.
        ///
        ///
        ///# logs
        ///로그를 기록 하는 곳입니다.
        ///xml 포맷으로 저장되며 https://github.com/LukePet/YALV/releases 을(를) 사용해 로그 내용을 확인할 수 있습니다.
        ///
        ///
        ///# databases
        ///데이[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_README {
            get {
                return ResourceManager.GetString("Text_README", resourceCulture);
            }
        }
    }
}
