//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntreev.Crema.Client.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ntreev.Crema.Client.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   _Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Lock과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Lock {
            get {
                return ResourceManager.GetString("Button_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selection of complex ranges is not possible.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotSelectComplexRanges {
            get {
                return ResourceManager.GetString("Exception_CannotSelectComplexRanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The range of columns to paste has been exceeded.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_ColumnRangeExceeded {
            get {
                return ResourceManager.GetString("Exception_ColumnRangeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; is read only.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_ItsReadOnly_Format {
            get {
                return ResourceManager.GetString("Exception_ItsReadOnly_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User or group to invite과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_AccessView1 {
            get {
                return ResourceManager.GetString("Label_AccessView1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Users or Groups with Access Permissions과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_AccessView2 {
            get {
                return ResourceManager.GetString("Label_AccessView2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Comment {
            get {
                return ResourceManager.GetString("Label_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel Edit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_CancelEdit {
            get {
                return ResourceManager.GetString("MenuItem_CancelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Copy...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Copy {
            get {
                return ResourceManager.GetString("MenuItem_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Delete {
            get {
                return ResourceManager.GetString("MenuItem_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End Edit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_EndEdit {
            get {
                return ResourceManager.GetString("MenuItem_EndEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Find과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Find {
            get {
                return ResourceManager.GetString("MenuItem_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Load...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Load {
            get {
                return ResourceManager.GetString("MenuItem_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Lock...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Lock {
            get {
                return ResourceManager.GetString("MenuItem_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Move...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Move {
            get {
                return ResourceManager.GetString("MenuItem_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _New Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_NewFolder {
            get {
                return ResourceManager.GetString("MenuItem_NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Rename...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Rename {
            get {
                return ResourceManager.GetString("MenuItem_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set _Authority...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_SetAuthority {
            get {
                return ResourceManager.GetString("MenuItem_SetAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set _Private과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_SetPrivate {
            get {
                return ResourceManager.GetString("MenuItem_SetPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set _Public과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_SetPublic {
            get {
                return ResourceManager.GetString("MenuItem_SetPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Unload...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Unload {
            get {
                return ResourceManager.GetString("MenuItem_Unload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Unlock과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Unlock {
            get {
                return ResourceManager.GetString("MenuItem_Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View Log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_ViewLog {
            get {
                return ResourceManager.GetString("MenuItem_ViewLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to delete row?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ConfirmToDeleteRow {
            get {
                return ResourceManager.GetString("Message_ConfirmToDeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to delete selected {0} rows?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ConfirmToDeleteSelectedRows_Format {
            get {
                return ResourceManager.GetString("Message_ConfirmToDeleteSelectedRows_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to reset field?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ConfirmToResetField {
            get {
                return ResourceManager.GetString("Message_ConfirmToResetField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to reset selected fields?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ConfirmToResetSelectedFields {
            get {
                return ResourceManager.GetString("Message_ConfirmToResetSelectedFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to set it to Private?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ConfirmToSetPrivate {
            get {
                return ResourceManager.GetString("Message_ConfirmToSetPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lock setting is in progress과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Locking {
            get {
                return ResourceManager.GetString("Message_Locking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting Authority과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_SettingAuthority {
            get {
                return ResourceManager.GetString("Title_SettingAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting Lock과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_SettingLock {
            get {
                return ResourceManager.GetString("Title_SettingLock", resourceCulture);
            }
        }
    }
}
