//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntreev.Crema.Client.Types.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ntreev.Crema.Client.Types.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Chang_e과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Change {
            get {
                return ResourceManager.GetString("Button_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Copy...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Copy {
            get {
                return ResourceManager.GetString("Button_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Create과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Find All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_FindAll {
            get {
                return ResourceManager.GetString("Button_FindAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Comment_Search {
            get {
                return ResourceManager.GetString("Comment_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Column {
            get {
                return ResourceManager.GetString("Label_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Comment {
            get {
                return ResourceManager.GetString("Label_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created DateTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CreatedDateTime {
            get {
                return ResourceManager.GetString("Label_CreatedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creator과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Creator {
            get {
                return ResourceManager.GetString("Label_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DateTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_DateTime {
            get {
                return ResourceManager.GetString("Label_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   find what과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_FindWhat {
            get {
                return ResourceManager.GetString("Label_FindWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   is flag과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_IsFlag {
            get {
                return ResourceManager.GetString("Label_IsFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   looking과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_LookIn {
            get {
                return ResourceManager.GetString("Label_LookIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified DateTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ModifiedDateTime {
            get {
                return ResourceManager.GetString("Label_ModifiedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modifier과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Modifier {
            get {
                return ResourceManager.GetString("Label_Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_NewName {
            get {
                return ResourceManager.GetString("Label_NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Original Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_OriginalName {
            get {
                return ResourceManager.GetString("Label_OriginalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Owner과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Owner {
            get {
                return ResourceManager.GetString("Label_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Path {
            get {
                return ResourceManager.GetString("Label_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Revision과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Revision {
            get {
                return ResourceManager.GetString("Label_Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Row {
            get {
                return ResourceManager.GetString("Label_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting DateTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_SettingDateTime {
            get {
                return ResourceManager.GetString("Label_SettingDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TargetFolder {
            get {
                return ResourceManager.GetString("Label_TargetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TypeName {
            get {
                return ResourceManager.GetString("Label_TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_User {
            get {
                return ResourceManager.GetString("Label_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UserID {
            get {
                return ResourceManager.GetString("Label_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Value {
            get {
                return ResourceManager.GetString("Label_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel Template Editing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_CancelTemplateEditing {
            get {
                return ResourceManager.GetString("MenuItem_CancelTemplateEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Delete {
            get {
                return ResourceManager.GetString("MenuItem_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Edit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Edit {
            get {
                return ResourceManager.GetString("MenuItem_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End Template Editing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_EndTemplateEditing {
            get {
                return ResourceManager.GetString("MenuItem_EndTemplateEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Find과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Find {
            get {
                return ResourceManager.GetString("MenuItem_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_FindAll {
            get {
                return ResourceManager.GetString("MenuItem_FindAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Lock과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Lock {
            get {
                return ResourceManager.GetString("MenuItem_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Move과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Move {
            get {
                return ResourceManager.GetString("MenuItem_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _New Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_NewFolder {
            get {
                return ResourceManager.GetString("MenuItem_NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _New Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_NewType {
            get {
                return ResourceManager.GetString("MenuItem_NewType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pre_view과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Preview {
            get {
                return ResourceManager.GetString("MenuItem_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quick Find과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_QuickFind {
            get {
                return ResourceManager.GetString("MenuItem_QuickFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Rename과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Rename {
            get {
                return ResourceManager.GetString("MenuItem_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select in type browser...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_SelectInTypeBrowser {
            get {
                return ResourceManager.GetString("MenuItem_SelectInTypeBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Authority과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_SetAuthority {
            get {
                return ResourceManager.GetString("MenuItem_SetAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Private과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_SetPrivate {
            get {
                return ResourceManager.GetString("MenuItem_SetPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Public과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_SetPublic {
            get {
                return ResourceManager.GetString("MenuItem_SetPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Type {
            get {
                return ResourceManager.GetString("MenuItem_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Unlock과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Unlock {
            get {
                return ResourceManager.GetString("MenuItem_Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_View {
            get {
                return ResourceManager.GetString("MenuItem_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ViewLog과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_ViewLog {
            get {
                return ResourceManager.GetString("MenuItem_ViewLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changing.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Changing {
            get {
                return ResourceManager.GetString("Message_Changing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to set it to Private?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ConfirmToSetPrivate {
            get {
                return ResourceManager.GetString("Message_ConfirmToSetPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Coping Type.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_CopingType {
            get {
                return ResourceManager.GetString("Message_CopingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creating과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Creating {
            get {
                return ResourceManager.GetString("Message_Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit has been exited by &apos;{0}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ExitEditByUser_Format {
            get {
                return ResourceManager.GetString("Message_ExitEditByUser_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receiving information.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ReceivingInfo {
            get {
                return ResourceManager.GetString("Message_ReceivingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type Copied.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_TypeCopied {
            get {
                return ResourceManager.GetString("Message_TypeCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access Information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_AccessInfo {
            get {
                return ResourceManager.GetString("Title_AccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_CopyType {
            get {
                return ResourceManager.GetString("Title_CopyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_DeleteType {
            get {
                return ResourceManager.GetString("Title_DeleteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Type Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_DeleteTypeFolder {
            get {
                return ResourceManager.GetString("Title_DeleteTypeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type Template Editing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_EditTypeTemplate {
            get {
                return ResourceManager.GetString("Title_EditTypeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Find {
            get {
                return ResourceManager.GetString("Title_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lock Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_LockInfo {
            get {
                return ResourceManager.GetString("Title_LockInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_MoveType {
            get {
                return ResourceManager.GetString("Title_MoveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move Type Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_MoveTypeFolder {
            get {
                return ResourceManager.GetString("Title_MoveTypeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_NewType {
            get {
                return ResourceManager.GetString("Title_NewType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Type Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_NewTypeFolder {
            get {
                return ResourceManager.GetString("Title_NewTypeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_RenameType {
            get {
                return ResourceManager.GetString("Title_RenameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename Type Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_RenameTypeFolder {
            get {
                return ResourceManager.GetString("Title_RenameTypeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Type {
            get {
                return ResourceManager.GetString("Title_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type Browser과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TypeBrowser {
            get {
                return ResourceManager.GetString("Title_TypeBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TypeInfo {
            get {
                return ResourceManager.GetString("Title_TypeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Types과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Types {
            get {
                return ResourceManager.GetString("Title_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Types Being Used과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TypesBeingUsed {
            get {
                return ResourceManager.GetString("Title_TypesBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View Log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_ViewLog {
            get {
                return ResourceManager.GetString("Title_ViewLog", resourceCulture);
            }
        }
    }
}
