//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntreev.Crema.Services.DataBaseCollectionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ntreev.com", ConfigurationName="DataBaseCollectionService.IDataBaseCollectionService", CallbackContract=typeof(Ntreev.Crema.Services.DataBaseCollectionService.IDataBaseCollectionServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    internal interface IDataBaseCollectionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDataBaseCollectionService/DefinitionType", ReplyAction="http://www.ntreev.com/IDataBaseCollectionService/DefinitionTypeResponse")]
        Ntreev.Crema.ServiceModel.ResultBase DefinitionType(Ntreev.Crema.ServiceModel.LogInfo[] param1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDataBaseCollectionService/Subscribe", ReplyAction="http://www.ntreev.com/IDataBaseCollectionService/SubscribeResponse")]
        Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DataBaseCollectionMetaData> Subscribe(System.Guid authenticationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDataBaseCollectionService/Unsubscribe", ReplyAction="http://www.ntreev.com/IDataBaseCollectionService/UnsubscribeResponse")]
        Ntreev.Crema.ServiceModel.ResultBase Unsubscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDataBaseCollectionService/SetPublic", ReplyAction="http://www.ntreev.com/IDataBaseCollectionService/SetPublicResponse")]
        Ntreev.Crema.ServiceModel.ResultBase SetPublic(string dataBaseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDataBaseCollectionService/SetPrivate", ReplyAction="http://www.ntreev.com/IDataBaseCollectionService/SetPrivateResponse")]
        Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.AccessInfo> SetPrivate(string dataBaseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDataBaseCollectionService/AddAccessMember", ReplyAction="http://www.ntreev.com/IDataBaseCollectionService/AddAccessMemberResponse")]
        Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.AccessMemberInfo> AddAccessMember(string dataBaseName, string memberID, Ntreev.Crema.ServiceModel.AccessType accessType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDataBaseCollectionService/SetAccessMember", ReplyAction="http://www.ntreev.com/IDataBaseCollectionService/SetAccessMemberResponse")]
        Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.AccessMemberInfo> SetAccessMember(string dataBaseName, string memberID, Ntreev.Crema.ServiceModel.AccessType accessType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDataBaseCollectionService/RemoveAccessMember", ReplyAction="http://www.ntreev.com/IDataBaseCollectionService/RemoveAccessMemberResponse")]
        Ntreev.Crema.ServiceModel.ResultBase RemoveAccessMember(string dataBaseName, string memberID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDataBaseCollectionService/Lock", ReplyAction="http://www.ntreev.com/IDataBaseCollectionService/LockResponse")]
        Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.LockInfo> Lock(string dataBaseName, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDataBaseCollectionService/Unlock", ReplyAction="http://www.ntreev.com/IDataBaseCollectionService/UnlockResponse")]
        Ntreev.Crema.ServiceModel.ResultBase Unlock(string dataBaseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDataBaseCollectionService/Load", ReplyAction="http://www.ntreev.com/IDataBaseCollectionService/LoadResponse")]
        Ntreev.Crema.ServiceModel.ResultBase Load(string dataBaseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDataBaseCollectionService/Unload", ReplyAction="http://www.ntreev.com/IDataBaseCollectionService/UnloadResponse")]
        Ntreev.Crema.ServiceModel.ResultBase Unload(string dataBaseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDataBaseCollectionService/Create", ReplyAction="http://www.ntreev.com/IDataBaseCollectionService/CreateResponse")]
        Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DataBaseInfo> Create(string dataBaseName, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDataBaseCollectionService/Copy", ReplyAction="http://www.ntreev.com/IDataBaseCollectionService/CopyResponse")]
        Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DataBaseInfo> Copy(string dataBaseName, string newDataBaseName, string comment, bool force);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDataBaseCollectionService/Rename", ReplyAction="http://www.ntreev.com/IDataBaseCollectionService/RenameResponse")]
        Ntreev.Crema.ServiceModel.ResultBase Rename(string dataBaseName, string newDataBaseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDataBaseCollectionService/Delete", ReplyAction="http://www.ntreev.com/IDataBaseCollectionService/DeleteResponse")]
        Ntreev.Crema.ServiceModel.ResultBase Delete(string dataBaseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDataBaseCollectionService/GetLog", ReplyAction="http://www.ntreev.com/IDataBaseCollectionService/GetLogResponse")]
        Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.LogInfo[]> GetLog(string dataBaseName, string revision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDataBaseCollectionService/Revert", ReplyAction="http://www.ntreev.com/IDataBaseCollectionService/RevertResponse")]
        Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DataBaseInfo> Revert(string dataBaseName, string revision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDataBaseCollectionService/BeginTransaction", ReplyAction="http://www.ntreev.com/IDataBaseCollectionService/BeginTransactionResponse")]
        Ntreev.Crema.ServiceModel.ResultBase BeginTransaction(string dataBaseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDataBaseCollectionService/EndTransaction", ReplyAction="http://www.ntreev.com/IDataBaseCollectionService/EndTransactionResponse")]
        Ntreev.Crema.ServiceModel.ResultBase EndTransaction(string dataBaseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDataBaseCollectionService/CancelTransaction", ReplyAction="http://www.ntreev.com/IDataBaseCollectionService/CancelTransactionResponse")]
        Ntreev.Crema.ServiceModel.ResultBase CancelTransaction(string dataBaseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ntreev.com/IDataBaseCollectionService/IsAlive", ReplyAction="http://www.ntreev.com/IDataBaseCollectionService/IsAliveResponse")]
        bool IsAlive();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IDataBaseCollectionServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDataBaseCollectionService/OnServiceClosed")]
        void OnServiceClosed(Ntreev.Library.SignatureDate signatureDate, Ntreev.Crema.ServiceModel.CloseInfo closeInfo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDataBaseCollectionService/OnDataBasesCreated")]
        void OnDataBasesCreated(Ntreev.Library.SignatureDate signatureDate, string[] dataBaseNames, Ntreev.Crema.ServiceModel.DataBaseInfo[] dataBaseInfos, string comment);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDataBaseCollectionService/OnDataBasesRenamed")]
        void OnDataBasesRenamed(Ntreev.Library.SignatureDate signatureDate, string[] dataBaseNames, string[] newDataBaseNames);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDataBaseCollectionService/OnDataBasesDeleted")]
        void OnDataBasesDeleted(Ntreev.Library.SignatureDate signatureDate, string[] dataBaseNames);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDataBaseCollectionService/OnDataBasesLoaded")]
        void OnDataBasesLoaded(Ntreev.Library.SignatureDate signatureDate, string[] dataBaseNames);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDataBaseCollectionService/OnDataBasesUnloaded")]
        void OnDataBasesUnloaded(Ntreev.Library.SignatureDate signatureDate, string[] dataBaseNames);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDataBaseCollectionService/OnDataBasesResetting")]
        void OnDataBasesResetting(Ntreev.Library.SignatureDate signatureDate, string[] dataBaseNames);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDataBaseCollectionService/OnDataBasesReset")]
        void OnDataBasesReset(Ntreev.Library.SignatureDate signatureDate, string[] dataBaseNames, Ntreev.Crema.ServiceModel.DomainMetaData[] metaDatas);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDataBaseCollectionService/OnDataBasesAuthenticationEntered" +
            "")]
        void OnDataBasesAuthenticationEntered(Ntreev.Library.SignatureDate signatureDate, string[] dataBaseNames, Ntreev.Crema.ServiceModel.AuthenticationInfo authenticationInfo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDataBaseCollectionService/OnDataBasesAuthenticationLeft")]
        void OnDataBasesAuthenticationLeft(Ntreev.Library.SignatureDate signatureDate, string[] dataBaseNames, Ntreev.Crema.ServiceModel.AuthenticationInfo authenticationInfo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDataBaseCollectionService/OnDataBasesInfoChanged")]
        void OnDataBasesInfoChanged(Ntreev.Library.SignatureDate signatureDate, Ntreev.Crema.ServiceModel.DataBaseInfo[] dataBaseInfos);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDataBaseCollectionService/OnDataBasesStateChanged")]
        void OnDataBasesStateChanged(Ntreev.Library.SignatureDate signatureDate, string[] dataBaseNames, Ntreev.Crema.ServiceModel.DataBaseState[] dataBaseStates);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDataBaseCollectionService/OnDataBasesAccessChanged")]
        void OnDataBasesAccessChanged(Ntreev.Library.SignatureDate signatureDate, Ntreev.Crema.ServiceModel.AccessChangeType changeType, Ntreev.Crema.ServiceModel.AccessInfo[] accessInfos, string[] memberIDs, Ntreev.Crema.ServiceModel.AccessType[] accessTypes);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ntreev.com/IDataBaseCollectionService/OnDataBasesLockChanged")]
        void OnDataBasesLockChanged(Ntreev.Library.SignatureDate signatureDate, Ntreev.Crema.ServiceModel.LockChangeType changeType, Ntreev.Crema.ServiceModel.LockInfo[] lockInfos, string[] comments);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IDataBaseCollectionServiceChannel : Ntreev.Crema.Services.DataBaseCollectionService.IDataBaseCollectionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class DataBaseCollectionServiceClient : System.ServiceModel.DuplexClientBase<Ntreev.Crema.Services.DataBaseCollectionService.IDataBaseCollectionService>, Ntreev.Crema.Services.DataBaseCollectionService.IDataBaseCollectionService {
        
        public DataBaseCollectionServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public DataBaseCollectionServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public DataBaseCollectionServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DataBaseCollectionServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DataBaseCollectionServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase DefinitionType(Ntreev.Crema.ServiceModel.LogInfo[] param1) {
            return base.Channel.DefinitionType(param1);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DataBaseCollectionMetaData> Subscribe(System.Guid authenticationToken) {
            return base.Channel.Subscribe(authenticationToken);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase Unsubscribe() {
            return base.Channel.Unsubscribe();
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase SetPublic(string dataBaseName) {
            return base.Channel.SetPublic(dataBaseName);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.AccessInfo> SetPrivate(string dataBaseName) {
            return base.Channel.SetPrivate(dataBaseName);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.AccessMemberInfo> AddAccessMember(string dataBaseName, string memberID, Ntreev.Crema.ServiceModel.AccessType accessType) {
            return base.Channel.AddAccessMember(dataBaseName, memberID, accessType);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.AccessMemberInfo> SetAccessMember(string dataBaseName, string memberID, Ntreev.Crema.ServiceModel.AccessType accessType) {
            return base.Channel.SetAccessMember(dataBaseName, memberID, accessType);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase RemoveAccessMember(string dataBaseName, string memberID) {
            return base.Channel.RemoveAccessMember(dataBaseName, memberID);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.LockInfo> Lock(string dataBaseName, string comment) {
            return base.Channel.Lock(dataBaseName, comment);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase Unlock(string dataBaseName) {
            return base.Channel.Unlock(dataBaseName);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase Load(string dataBaseName) {
            return base.Channel.Load(dataBaseName);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase Unload(string dataBaseName) {
            return base.Channel.Unload(dataBaseName);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DataBaseInfo> Create(string dataBaseName, string comment) {
            return base.Channel.Create(dataBaseName, comment);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DataBaseInfo> Copy(string dataBaseName, string newDataBaseName, string comment, bool force) {
            return base.Channel.Copy(dataBaseName, newDataBaseName, comment, force);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase Rename(string dataBaseName, string newDataBaseName) {
            return base.Channel.Rename(dataBaseName, newDataBaseName);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase Delete(string dataBaseName) {
            return base.Channel.Delete(dataBaseName);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.LogInfo[]> GetLog(string dataBaseName, string revision) {
            return base.Channel.GetLog(dataBaseName, revision);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase<Ntreev.Crema.ServiceModel.DataBaseInfo> Revert(string dataBaseName, string revision) {
            return base.Channel.Revert(dataBaseName, revision);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase BeginTransaction(string dataBaseName) {
            return base.Channel.BeginTransaction(dataBaseName);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase EndTransaction(string dataBaseName) {
            return base.Channel.EndTransaction(dataBaseName);
        }
        
        public Ntreev.Crema.ServiceModel.ResultBase CancelTransaction(string dataBaseName) {
            return base.Channel.CancelTransaction(dataBaseName);
        }
        
        public bool IsAlive() {
            return base.Channel.IsAlive();
        }
    }
}
