//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntreev.Crema.Client.Users.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ntreev.Crema.Client.Users.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   _Change과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Change {
            get {
                return ResourceManager.GetString("Button_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Create과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Reply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Reply {
            get {
                return ResourceManager.GetString("Button_Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Send과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Send {
            get {
                return ResourceManager.GetString("Button_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authority과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Authority {
            get {
                return ResourceManager.GetString("Label_Authority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Banned DateTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_BanDateTime {
            get {
                return ResourceManager.GetString("Label_BanDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Banned Reason과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_BanReason {
            get {
                return ResourceManager.GetString("Label_BanReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blocker과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Blocker {
            get {
                return ResourceManager.GetString("Label_Blocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created DateTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CreatedDateTime {
            get {
                return ResourceManager.GetString("Label_CreatedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creator과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Creator {
            get {
                return ResourceManager.GetString("Label_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CurrentPassword {
            get {
                return ResourceManager.GetString("Label_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ID {
            get {
                return ResourceManager.GetString("Label_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kicked Reason과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_KickReason {
            get {
                return ResourceManager.GetString("Label_KickReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified DateTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ModifiedDateTime {
            get {
                return ResourceManager.GetString("Label_ModifiedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modifier과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Modifier {
            get {
                return ResourceManager.GetString("Label_Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_NewPassword {
            get {
                return ResourceManager.GetString("Label_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_PasswordConfirm {
            get {
                return ResourceManager.GetString("Label_PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Path {
            get {
                return ResourceManager.GetString("Label_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Authority과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UserAuthority {
            get {
                return ResourceManager.GetString("Label_UserAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UserFolder {
            get {
                return ResourceManager.GetString("Label_UserFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UserID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UserID {
            get {
                return ResourceManager.GetString("Label_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UserName {
            get {
                return ResourceManager.GetString("Label_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ban과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Ban {
            get {
                return ResourceManager.GetString("MenuItem_Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Change...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Change {
            get {
                return ResourceManager.GetString("MenuItem_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change _Password...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_ChangePassword {
            get {
                return ResourceManager.GetString("MenuItem_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Delete...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Delete {
            get {
                return ResourceManager.GetString("MenuItem_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kick과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Kick {
            get {
                return ResourceManager.GetString("MenuItem_Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Move...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Move {
            get {
                return ResourceManager.GetString("MenuItem_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _New Folder...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_NewFolder {
            get {
                return ResourceManager.GetString("MenuItem_NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _New User...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_NewUser {
            get {
                return ResourceManager.GetString("MenuItem_NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rena_me...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Rename {
            get {
                return ResourceManager.GetString("MenuItem_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send Message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_SendMessage {
            get {
                return ResourceManager.GetString("MenuItem_SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Owner과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_SetOwner {
            get {
                return ResourceManager.GetString("MenuItem_SetOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unban과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Unban {
            get {
                return ResourceManager.GetString("MenuItem_Unban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changing.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Change {
            get {
                return ResourceManager.GetString("Message_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changed completed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ChangeComplete {
            get {
                return ResourceManager.GetString("Message_ChangeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adding User.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_NewUser {
            get {
                return ResourceManager.GetString("Message_NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User added.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_NewUserComplete {
            get {
                return ResourceManager.GetString("Message_NewUserComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sending message.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_SendMessage {
            get {
                return ResourceManager.GetString("Message_SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Administrator Message: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_AdministratorMessage_Format {
            get {
                return ResourceManager.GetString("Title_AdministratorMessage_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ban Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_BanInfo {
            get {
                return ResourceManager.GetString("Title_BanInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ban User과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_BanUser {
            get {
                return ResourceManager.GetString("Title_BanUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_ChangePassword {
            get {
                return ResourceManager.GetString("Title_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change User Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_ChangeUserInfo {
            get {
                return ResourceManager.GetString("Title_ChangeUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DataBase Users과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_DataBaseUsers {
            get {
                return ResourceManager.GetString("Title_DataBaseUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete User과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_DeleteUser {
            get {
                return ResourceManager.GetString("Title_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete User Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_DeleteUserFolder {
            get {
                return ResourceManager.GetString("Title_DeleteUserFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kick Editor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_KickEditor {
            get {
                return ResourceManager.GetString("Title_KickEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kick User과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_KickUser {
            get {
                return ResourceManager.GetString("Title_KickUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move User과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_MoveUser {
            get {
                return ResourceManager.GetString("Title_MoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move User Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_MoveUserFolder {
            get {
                return ResourceManager.GetString("Title_MoveUserFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New User과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_NewUser {
            get {
                return ResourceManager.GetString("Title_NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New User Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_NewUserFolder {
            get {
                return ResourceManager.GetString("Title_NewUserFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notify Message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_NotifyMessage {
            get {
                return ResourceManager.GetString("Title_NotifyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename User Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_RenameUserFolder {
            get {
                return ResourceManager.GetString("Title_RenameUserFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send Message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_SendMessage {
            get {
                return ResourceManager.GetString("Title_SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Domain List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_UserDomainList {
            get {
                return ResourceManager.GetString("Title_UserDomainList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_UserInfo {
            get {
                return ResourceManager.GetString("Title_UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Users과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Users {
            get {
                return ResourceManager.GetString("Title_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Users who are editing contents과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_UsersEditingContent {
            get {
                return ResourceManager.GetString("Title_UsersEditingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Users who are editing template과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_UsersEditingTemplate {
            get {
                return ResourceManager.GetString("Title_UsersEditingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View Message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_ViewMessage {
            get {
                return ResourceManager.GetString("Title_ViewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changes exist.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tooltip_HasChanges {
            get {
                return ResourceManager.GetString("Tooltip_HasChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notify Message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tooltip_Notify {
            get {
                return ResourceManager.GetString("Tooltip_Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Owner과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tooltip_Owner {
            get {
                return ResourceManager.GetString("Tooltip_Owner", resourceCulture);
            }
        }
    }
}
