//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntreev.Crema.Comparer.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ntreev.Crema.Comparer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   설명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Comment {
            get {
                return ResourceManager.GetString("Label_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 변경 일자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ContentModifiedDateTime {
            get {
                return ResourceManager.GetString("Label_ContentModifiedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 변경자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ContentModifier {
            get {
                return ResourceManager.GetString("Label_ContentModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   생성 일자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CreatedDateTime {
            get {
                return ResourceManager.GetString("Label_CreatedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   생성자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Creator {
            get {
                return ResourceManager.GetString("Label_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   플래그 집합과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_IsFlag {
            get {
                return ResourceManager.GetString("Label_IsFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ModifiedDateTime {
            get {
                return ResourceManager.GetString("Label_ModifiedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경 일자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Modifier {
            get {
                return ResourceManager.GetString("Label_Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Path {
            get {
                return ResourceManager.GetString("Label_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   테이블 이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TableName {
            get {
                return ResourceManager.GetString("Label_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   태그과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Tags {
            get {
                return ResourceManager.GetString("Label_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   부모 템플릿과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TemplatedParent {
            get {
                return ResourceManager.GetString("Label_TemplatedParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   형태 변경 일자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TemplateModifiedDateTime {
            get {
                return ResourceManager.GetString("Label_TemplateModifiedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   형태 변경자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TemplateModifier {
            get {
                return ResourceManager.GetString("Label_TemplateModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   123
        ///12
        ///1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   123
        ///1
        ///1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   컬럼 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_ColumnInfo {
            get {
                return ResourceManager.GetString("Title_ColumnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   테이블 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TableInfo {
            get {
                return ResourceManager.GetString("Title_TableInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   타입 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TypeInfo {
            get {
                return ResourceManager.GetString("Title_TypeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   해결되지 않은 항목들과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_UnresolvedItems {
            get {
                return ResourceManager.GetString("Title_UnresolvedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   닫기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tool_Close {
            get {
                return ResourceManager.GetString("Tool_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   열기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tool_Open {
            get {
                return ResourceManager.GetString("Tool_Open", resourceCulture);
            }
        }
    }
}
