//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntreev.Crema.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ntreev.Crema.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add item to left side과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Command_AddItemToLeftSide {
            get {
                return ResourceManager.GetString("Command_AddItemToLeftSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add item to right side과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Command_AddItemToRightSide {
            get {
                return ResourceManager.GetString("Command_AddItemToRightSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy field to left side과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Command_CopyFieldToLeftSide {
            get {
                return ResourceManager.GetString("Command_CopyFieldToLeftSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy field to right side과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Command_CopyFieldToRightSide {
            get {
                return ResourceManager.GetString("Command_CopyFieldToRightSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy item to left side과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Command_CopyItemToLeftSide {
            get {
                return ResourceManager.GetString("Command_CopyItemToLeftSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy item to right side과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Command_CopyItemToRightSide {
            get {
                return ResourceManager.GetString("Command_CopyItemToRightSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Command_Delete {
            get {
                return ResourceManager.GetString("Command_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Command_Merge {
            get {
                return ResourceManager.GetString("Command_Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next difference field과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Command_NextDifferenceField {
            get {
                return ResourceManager.GetString("Command_NextDifferenceField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next difference item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Command_NextDifferenceItem {
            get {
                return ResourceManager.GetString("Command_NextDifferenceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous difference field과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Command_PrevDifferenceField {
            get {
                return ResourceManager.GetString("Command_PrevDifferenceField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous difference item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Command_PrevDifferenceItem {
            get {
                return ResourceManager.GetString("Command_PrevDifferenceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resolve과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Command_Resolve {
            get {
                return ResourceManager.GetString("Command_Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Comment {
            get {
                return ResourceManager.GetString("Label_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created DateTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CreatedDateTime {
            get {
                return ResourceManager.GetString("Label_CreatedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creation Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CreationInfo {
            get {
                return ResourceManager.GetString("Label_CreationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creator과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Creator {
            get {
                return ResourceManager.GetString("Label_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IsFlag과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_IsFlag {
            get {
                return ResourceManager.GetString("Label_IsFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modification Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ModificationInfo {
            get {
                return ResourceManager.GetString("Label_ModificationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified DateTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ModifiedDateTime {
            get {
                return ResourceManager.GetString("Label_ModifiedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modifier과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Modifier {
            get {
                return ResourceManager.GetString("Label_Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TableName {
            get {
                return ResourceManager.GetString("Label_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tags과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Tags {
            get {
                return ResourceManager.GetString("Label_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TypeName {
            get {
                return ResourceManager.GetString("Label_TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Value {
            get {
                return ResourceManager.GetString("Label_Value", resourceCulture);
            }
        }
    }
}
