//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntreev.Crema.Client.SmartSet.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ntreev.Crema.Client.SmartSet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   _Add과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cre_ate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Move과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Move {
            get {
                return ResourceManager.GetString("Button_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Whether or not he is involved in editing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Comment_IsMember {
            get {
                return ResourceManager.GetString("Comment_IsMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Case sensitive과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CaseSensitive {
            get {
                return ResourceManager.GetString("Label_CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CategoryName {
            get {
                return ResourceManager.GetString("Label_CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CategoryPath {
            get {
                return ResourceManager.GetString("Label_CategoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CurrentPath {
            get {
                return ResourceManager.GetString("Label_CurrentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_FolderName {
            get {
                return ResourceManager.GetString("Label_FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Item Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ItemName {
            get {
                return ResourceManager.GetString("Label_ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rules과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Rule {
            get {
                return ResourceManager.GetString("Label_Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   String to compare과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_StringtoCompare {
            get {
                return ResourceManager.GetString("Label_StringtoCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TableName {
            get {
                return ResourceManager.GetString("Label_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TargetPath {
            get {
                return ResourceManager.GetString("Label_TargetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use glob pattern과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UseGlobPattern {
            get {
                return ResourceManager.GetString("Label_UseGlobPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add to bookmark과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_AddToBookmark {
            get {
                return ResourceManager.GetString("MenuItem_AddToBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy to clipboard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_CopyList {
            get {
                return ResourceManager.GetString("MenuItem_CopyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Delete {
            get {
                return ResourceManager.GetString("MenuItem_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Edit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Edit {
            get {
                return ResourceManager.GetString("MenuItem_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Move과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Move {
            get {
                return ResourceManager.GetString("MenuItem_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move Bookmark과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_MoveBookmark {
            get {
                return ResourceManager.GetString("MenuItem_MoveBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _New Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_NewFolder {
            get {
                return ResourceManager.GetString("MenuItem_NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _New SmartSet과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_NewSmartSet {
            get {
                return ResourceManager.GetString("MenuItem_NewSmartSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove from bookmark과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_RemoveFromBookmark {
            get {
                return ResourceManager.GetString("MenuItem_RemoveFromBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Rename과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Rename {
            get {
                return ResourceManager.GetString("MenuItem_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Base Table과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_BaseTable {
            get {
                return ResourceManager.GetString("Text_BaseTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Child Table과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_ChildTable {
            get {
                return ResourceManager.GetString("Text_ChildTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Derived Table과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_DerivedTable {
            get {
                return ResourceManager.GetString("Text_DerivedTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Is Being Edited과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_IsBeingEdited {
            get {
                return ResourceManager.GetString("Text_IsBeingEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Is Begin Setup과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_IsBeingSetup {
            get {
                return ResourceManager.GetString("Text_IsBeingSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Is Flag과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_IsFlag {
            get {
                return ResourceManager.GetString("Text_IsFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Is Member과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_IsMember {
            get {
                return ResourceManager.GetString("Text_IsMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_None {
            get {
                return ResourceManager.GetString("Text_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_Now {
            get {
                return ResourceManager.GetString("Text_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specific time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_SpecificTime {
            get {
                return ResourceManager.GetString("Text_SpecificTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Today과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_Today {
            get {
                return ResourceManager.GetString("Text_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Bookmark과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_AddBookmark {
            get {
                return ResourceManager.GetString("Title_AddBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bookmark과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Bookmark {
            get {
                return ResourceManager.GetString("Title_Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column Count과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_ColumnCount {
            get {
                return ResourceManager.GetString("Title_ColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column DataType과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_ColumnDataType {
            get {
                return ResourceManager.GetString("Title_ColumnDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_ColumnName {
            get {
                return ResourceManager.GetString("Title_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DateTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_DateTime {
            get {
                return ResourceManager.GetString("Title_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Smart Collection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_EditSmartCollection {
            get {
                return ResourceManager.GetString("Title_EditSmartCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key Count과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_KeyCount {
            get {
                return ResourceManager.GetString("Title_KeyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move Bookmark과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_MoveBookmark {
            get {
                return ResourceManager.GetString("Title_MoveBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Category과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_NewCategory {
            get {
                return ResourceManager.GetString("Title_NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Smart Collection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_NewSmartCollection {
            get {
                return ResourceManager.GetString("Title_NewSmartCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SmartSet과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_SmartSet {
            get {
                return ResourceManager.GetString("Title_SmartSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table Attributes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TableAttributes {
            get {
                return ResourceManager.GetString("Title_TableAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table Content Modified DateTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TableContentModifiedDateTime {
            get {
                return ResourceManager.GetString("Title_TableContentModifiedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table Content Modifier과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TableContentModifier {
            get {
                return ResourceManager.GetString("Title_TableContentModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table Created DateTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TableCreatedDateTime {
            get {
                return ResourceManager.GetString("Title_TableCreatedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table Creator과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TableCreatedUser {
            get {
                return ResourceManager.GetString("Title_TableCreatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table Is Locked과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TableIsLocked {
            get {
                return ResourceManager.GetString("Title_TableIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TableName {
            get {
                return ResourceManager.GetString("Title_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table Smart Collection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TableSmartCollection {
            get {
                return ResourceManager.GetString("Title_TableSmartCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table States과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TableStates {
            get {
                return ResourceManager.GetString("Title_TableStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table Tags과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TableTags {
            get {
                return ResourceManager.GetString("Title_TableTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table Template Modified DateTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TableTemplateModifiedDateTime {
            get {
                return ResourceManager.GetString("Title_TableTemplateModifiedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table Template Modifier과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TableTemplateModifier {
            get {
                return ResourceManager.GetString("Title_TableTemplateModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tags과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Tags {
            get {
                return ResourceManager.GetString("Title_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type Attributes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TypeAttributes {
            get {
                return ResourceManager.GetString("Title_TypeAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type Created DateTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TypeCreatedDateTime {
            get {
                return ResourceManager.GetString("Title_TypeCreatedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type Creator과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TypeCreator {
            get {
                return ResourceManager.GetString("Title_TypeCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type Modified DateTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TypeModifiedDateTime {
            get {
                return ResourceManager.GetString("Title_TypeModifiedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type Modifier과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TypeModifier {
            get {
                return ResourceManager.GetString("Title_TypeModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TypeName {
            get {
                return ResourceManager.GetString("Title_TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type Smart Collection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TypeSmartCollection {
            get {
                return ResourceManager.GetString("Title_TypeSmartCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type States과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TypeState {
            get {
                return ResourceManager.GetString("Title_TypeState", resourceCulture);
            }
        }
    }
}
