//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntreev.Crema.Client.Tables.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ntreev.Crema.Client.Tables.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   _Change과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Change {
            get {
                return ResourceManager.GetString("Button_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Copy...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Copy {
            get {
                return ResourceManager.GetString("Button_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Create과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Find과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Find {
            get {
                return ResourceManager.GetString("Button_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Find All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_FindAll {
            get {
                return ResourceManager.GetString("Button_FindAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter word to find과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Comment_EnterWordToFind {
            get {
                return ResourceManager.GetString("Comment_EnterWordToFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Column {
            get {
                return ResourceManager.GetString("Label_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Comment {
            get {
                return ResourceManager.GetString("Label_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Content Modified DateTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ContentModifiedDateTime {
            get {
                return ResourceManager.GetString("Label_ContentModifiedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Content Modifier과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ContentModifier {
            get {
                return ResourceManager.GetString("Label_ContentModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CopyData {
            get {
                return ResourceManager.GetString("Label_CopyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created DateTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_CreatedDateTime {
            get {
                return ResourceManager.GetString("Label_CreatedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creator과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Creator {
            get {
                return ResourceManager.GetString("Label_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DateTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_DateTime {
            get {
                return ResourceManager.GetString("Label_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   find what과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_FindWhat {
            get {
                return ResourceManager.GetString("Label_FindWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   looking과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_LookIn {
            get {
                return ResourceManager.GetString("Label_LookIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified DateTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ModifiedDateTime {
            get {
                return ResourceManager.GetString("Label_ModifiedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modifier과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Modifier {
            get {
                return ResourceManager.GetString("Label_Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_NewName {
            get {
                return ResourceManager.GetString("Label_NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Original Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_OriginalName {
            get {
                return ResourceManager.GetString("Label_OriginalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Owner과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Owner {
            get {
                return ResourceManager.GetString("Label_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Path {
            get {
                return ResourceManager.GetString("Label_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Revision과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Revision {
            get {
                return ResourceManager.GetString("Label_Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Row {
            get {
                return ResourceManager.GetString("Label_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting DateTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_SettingDateTime {
            get {
                return ResourceManager.GetString("Label_SettingDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TableName {
            get {
                return ResourceManager.GetString("Label_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tags과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Tags {
            get {
                return ResourceManager.GetString("Label_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TargetFolder {
            get {
                return ResourceManager.GetString("Label_TargetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parent Template과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TemplatedParent {
            get {
                return ResourceManager.GetString("Label_TemplatedParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Template Modified DateTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TemplateModifiedDateTime {
            get {
                return ResourceManager.GetString("Label_TemplateModifiedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Template Modifier과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TemplateModifier {
            get {
                return ResourceManager.GetString("Label_TemplateModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_User {
            get {
                return ResourceManager.GetString("Label_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UserID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UserID {
            get {
                return ResourceManager.GetString("Label_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Template과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_UseTemplate {
            get {
                return ResourceManager.GetString("Label_UseTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Value {
            get {
                return ResourceManager.GetString("Label_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel Content Editing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_CancelContentEditing {
            get {
                return ResourceManager.GetString("MenuItem_CancelContentEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel Template Editing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_CancelTemplateEditing {
            get {
                return ResourceManager.GetString("MenuItem_CancelTemplateEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Copy Table...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_CopyTable {
            get {
                return ResourceManager.GetString("MenuItem_CopyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Delete...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Delete {
            get {
                return ResourceManager.GetString("MenuItem_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Edit Content과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_EditContent {
            get {
                return ResourceManager.GetString("MenuItem_EditContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit _Template...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_EditTemplate {
            get {
                return ResourceManager.GetString("MenuItem_EditTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End Content Editing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_EndContentEditing {
            get {
                return ResourceManager.GetString("MenuItem_EndContentEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End Template Editing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_EndTemplateEditing {
            get {
                return ResourceManager.GetString("MenuItem_EndTemplateEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Find...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Find {
            get {
                return ResourceManager.GetString("MenuItem_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_FindAll {
            get {
                return ResourceManager.GetString("MenuItem_FindAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Inherite Table...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_InheritTable {
            get {
                return ResourceManager.GetString("MenuItem_InheritTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Lock...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Lock {
            get {
                return ResourceManager.GetString("MenuItem_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Move...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Move {
            get {
                return ResourceManager.GetString("MenuItem_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New _ChildTable...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_NewChildTable {
            get {
                return ResourceManager.GetString("MenuItem_NewChildTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New _Folder...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_NewFolder {
            get {
                return ResourceManager.GetString("MenuItem_NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New _Table...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_NewTable {
            get {
                return ResourceManager.GetString("MenuItem_NewTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pre_view...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Preview {
            get {
                return ResourceManager.GetString("MenuItem_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quick _Find과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_QuickFind {
            get {
                return ResourceManager.GetString("MenuItem_QuickFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Rename...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Rename {
            get {
                return ResourceManager.GetString("MenuItem_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select in table browser...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_SelectInTableBrowser {
            get {
                return ResourceManager.GetString("MenuItem_SelectInTableBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set _Authority...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_SetAuthority {
            get {
                return ResourceManager.GetString("MenuItem_SetAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set _Private과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_SetPrivate {
            get {
                return ResourceManager.GetString("MenuItem_SetPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set _Public과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_SetPublic {
            get {
                return ResourceManager.GetString("MenuItem_SetPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tabl_e과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Table {
            get {
                return ResourceManager.GetString("MenuItem_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tags과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Tags {
            get {
                return ResourceManager.GetString("MenuItem_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_TagsAll {
            get {
                return ResourceManager.GetString("MenuItem_TagsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Client과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_TagsClient {
            get {
                return ResourceManager.GetString("MenuItem_TagsClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_TagsServer {
            get {
                return ResourceManager.GetString("MenuItem_TagsServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unused과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_TagsUnused {
            get {
                return ResourceManager.GetString("MenuItem_TagsUnused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Unlock과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Unlock {
            get {
                return ResourceManager.GetString("MenuItem_Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View Content과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_ViewContent {
            get {
                return ResourceManager.GetString("MenuItem_ViewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View Log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_ViewLog {
            get {
                return ResourceManager.GetString("MenuItem_ViewLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View Template과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_ViewTemplate {
            get {
                return ResourceManager.GetString("MenuItem_ViewTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changing.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Changing {
            get {
                return ResourceManager.GetString("Message_Changing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel editing the contents. Items that are not saved will disappear. Would you like to go on?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ConfirmToCancelContentEditing {
            get {
                return ResourceManager.GetString("Message_ConfirmToCancelContentEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finishes the contents of the contents. Would you like to go on?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ConfirmToEndContentEditing {
            get {
                return ResourceManager.GetString("Message_ConfirmToEndContentEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to set it to Private?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ConfirmToSetPrivate {
            get {
                return ResourceManager.GetString("Message_ConfirmToSetPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copying.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Coping {
            get {
                return ResourceManager.GetString("Message_Coping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creating.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Creating {
            get {
                return ResourceManager.GetString("Message_Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit has been exited by &apos;{0}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ExitEditByUser_Format {
            get {
                return ResourceManager.GetString("Message_ExitEditByUser_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It&apos;s ReadOnly과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_IsReadOnly {
            get {
                return ResourceManager.GetString("Message_IsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_LoadingData {
            get {
                return ResourceManager.GetString("Message_LoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receiving information.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ReceivingInfo {
            get {
                return ResourceManager.GetString("Message_ReceivingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saving.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Saving {
            get {
                return ResourceManager.GetString("Message_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access Information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_AccessInfo {
            get {
                return ResourceManager.GetString("Title_AccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Base Table과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_BaseTable {
            get {
                return ResourceManager.GetString("Title_BaseTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy Table과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_CopyTable {
            get {
                return ResourceManager.GetString("Title_CopyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Table과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_DeleteTable {
            get {
                return ResourceManager.GetString("Title_DeleteTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Table Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_DeleteTableFolder {
            get {
                return ResourceManager.GetString("Title_DeleteTableFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Derived Tables과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_DerivedTable {
            get {
                return ResourceManager.GetString("Title_DerivedTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Find {
            get {
                return ResourceManager.GetString("Title_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inherit Table과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_InheritTable {
            get {
                return ResourceManager.GetString("Title_InheritTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lock Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_LockInfo {
            get {
                return ResourceManager.GetString("Title_LockInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move Table과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_MoveTable {
            get {
                return ResourceManager.GetString("Title_MoveTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move Table Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_MoveTableFolder {
            get {
                return ResourceManager.GetString("Title_MoveTableFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Child Table과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_NewChildTable {
            get {
                return ResourceManager.GetString("Title_NewChildTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Table과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_NewTable {
            get {
                return ResourceManager.GetString("Title_NewTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Table Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_NewTableFolder {
            get {
                return ResourceManager.GetString("Title_NewTableFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename Table과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_RenameTable {
            get {
                return ResourceManager.GetString("Title_RenameTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename Table Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_RenameTableFolder {
            get {
                return ResourceManager.GetString("Title_RenameTableFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table Browser과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TableBrowser {
            get {
                return ResourceManager.GetString("Title_TableBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TableColumnInfo {
            get {
                return ResourceManager.GetString("Title_TableColumnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TableInfo {
            get {
                return ResourceManager.GetString("Title_TableInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tables과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Tables {
            get {
                return ResourceManager.GetString("Title_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tables being used과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TablesBeingUsed {
            get {
                return ResourceManager.GetString("Title_TablesBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Editing Table Template과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_TableTemplateEditing {
            get {
                return ResourceManager.GetString("Title_TableTemplateEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View Log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_ViewLog {
            get {
                return ResourceManager.GetString("Title_ViewLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View Table Template과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_ViewTableTemplate {
            get {
                return ResourceManager.GetString("Title_ViewTableTemplate", resourceCulture);
            }
        }
    }
}
