//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntreev.Crema.Client.Converters.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ntreev.Crema.Client.Converters.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   _Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Export과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Export {
            get {
                return ResourceManager.GetString("Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Import과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Import {
            get {
                return ResourceManager.GetString("Button_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter a comment for the import.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Comment_CommentForImporting {
            get {
                return ResourceManager.GetString("Comment_CommentForImporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Comment {
            get {
                return ResourceManager.GetString("Label_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export by folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ExportByFolder {
            get {
                return ResourceManager.GetString("Label_ExportByFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exporting Information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ExportingInformation {
            get {
                return ResourceManager.GetString("Label_ExportingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ExportingType {
            get {
                return ResourceManager.GetString("Label_ExportingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export One Table To One File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ExportOneTableToOneFile {
            get {
                return ResourceManager.GetString("Label_ExportOneTableToOneFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Importing Information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ImportingImformation {
            get {
                return ResourceManager.GetString("Label_ImportingImformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ImportingType {
            get {
                return ResourceManager.GetString("Label_ImportingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Include date in file name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_IncludeDate {
            get {
                return ResourceManager.GetString("Label_IncludeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Omit Tags and Enabled과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_OmitAttribute {
            get {
                return ResourceManager.GetString("Label_OmitAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Omit Creation and Modification Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_OmitSignatureDate {
            get {
                return ResourceManager.GetString("Label_OmitSignatureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date Format과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_OutputDateFormat {
            get {
                return ResourceManager.GetString("Label_OutputDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Path {
            get {
                return ResourceManager.GetString("Label_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select _All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_SelectAll {
            get {
                return ResourceManager.GetString("Label_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Export과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Export {
            get {
                return ResourceManager.GetString("MenuItem_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Import과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Import {
            get {
                return ResourceManager.GetString("MenuItem_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canceling.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Canceling {
            get {
                return ResourceManager.GetString("Message_Canceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exported.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Exported {
            get {
                return ResourceManager.GetString("Message_Exported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exporting Data.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ExportingData {
            get {
                return ResourceManager.GetString("Message_ExportingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exporting Data : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ExportingDataFormat {
            get {
                return ResourceManager.GetString("Message_ExportingDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Imported.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Imported {
            get {
                return ResourceManager.GetString("Message_Imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Importing.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Importing {
            get {
                return ResourceManager.GetString("Message_Importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No tables can be exported.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_NoneTablesToExport {
            get {
                return ResourceManager.GetString("Message_NoneTablesToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receiving Data.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ReceivingData {
            get {
                return ResourceManager.GetString("Message_ReceivingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receiving Data : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_ReceivingDataFormat {
            get {
                return ResourceManager.GetString("Message_ReceivingDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Export {
            get {
                return ResourceManager.GetString("Title_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Import {
            get {
                return ResourceManager.GetString("Title_Import", resourceCulture);
            }
        }
    }
}
